### ISSUE TITLE
Homing does not work on 2 axis machine with hard limits

### ISSUE THREAD

**Issue by Poppy45** [makerbase-mks/MKS-DLC32#1]
homing does not work on 2 axis machine with hard limits .so need to modify firmware to stop x axis homing as per grbl instructions'.

**Comment by mks-viva** [comment]
Please provide a video when your manchie homing.

**Comment by Poppy45** [comment]
https://user-images.githubusercontent.com/64296414/132287709-65737b8e-4093-4b42-bb63-c7bf4416c18f.mp4


https://user-images.githubusercontent.com/64296414/132287731-7ec0ba69-0673-497d-9a13-53f34aea8c7f.mp4

goes into alarm 8 as tries to home z axis but does not exist

**Comment by Poppy45** [comment]
closed by mistake

**Comment by Poppy45** [comment]
as per link https://github.com/gnea/grbl/wiki/Two-Axis-System-Considerations

**Comment by solawc** [comment]
> as per link https://github.com/gnea/grbl/wiki/Two-Axis-System-Considerations

Hello, although dlc32 supports the instructions and upper computer of grbl, some operations have been changed. For dlc32 just delivered, Z-axis and z-limit are not used in the firmware, so they will not start the effect. Please check whether the level setting of a lower limit bit is correct

**Comment by Poppy45** [comment]
[DLC32 setting.txt](https://github.com/makerbase-mks/MKS-DLC32/files/7120574/DLC32.setting.txt)
Thanks that was i was asking. Please explain what you mean by  level setting of a lower limit bit is correct. attached is my setting in txt file

**Comment by Poppy45** [comment]
got it working using NC switches need to have $5=0 not 1 which is reverse of grbl setting

**Comment by Poppy45** [comment]
thanks for non help

**Comment by Poppy45** [comment]
read the solution above $5=0 with NC switches not as per grbl instructions which states $5=1
