### ISSUE TITLE
Power Module Footprint and schematic

### ISSUE THREAD

**Issue by NicNatTech** [makerbase-mks/MKS-DLC32#100]
I question whether the footprint for the motor drivers on page 7 of the wiring diagram, as well as its schematic are correct?
My first board blew the driver on socket # (Z) JUST on power up.
Please confirm

**Comment by MKS-hosiey** [comment]
Did you install the driver backwards? Confirm the wiring diagram is correct

**Comment by NicNatTech** [comment]
Per the Wiring Document  
![image](https://user-images.githubusercontent.com/97560435/149159442-5769100f-872a-4880-aae0-71eb2823b774.png)
Per Standard and schematic
![image](https://user-images.githubusercontent.com/97560435/149159532-9e4955f8-98a9-44f1-9ed5-d3cec9d28f90.png)
Notice difference in pins 11-14
To clarify the only board I received blew two drivers on the z port on power up with no motors connected.

If I recall it had a black x on the underneath side of the port. (I will look tonight)
I have a replacement and others boards on order. (I believe this module is leaps and bounds ahead of the competition) 
Steps taken with board 
1) update firmware for CNC and  
2) install three motor drivers (XYZ)  (why did board only come with two drivers? 
3) power on with no motors connected( Z port blew two drivers X&Y no issues). 

I went looking at github documents and noticed the discrepancy.

**Comment by MKS-hosiey** [comment]
The 1A ,1B and 2A and 2B ，will only lead to different direction, which will not cause burning driven.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 12, 2022 22:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [makerbase-mks/MKS-DLC32] Power Module Footprint and schematic(Issue #100)




 
Per the Wiring Document
 
 Per Standard and schematic
 
 Notice difference in pins 11-14
 To clarify the only board I received blew two drivers on the z port on power up with no motors connected.
 
If I recall it had a black x on the underneath side of the port. (I will look tonight)
 I have a replacement and others boards on order. (I believe this module is leaps and bounds ahead of the competition)
 Steps taken with board
  
update firmware for CNC and 

install three motor drivers (XYZ)  (why did board only come with two drivers? 

power on with no motors connected( Z port blew two drivers X&amp;Y no issues). 
 
I went looking at github documents and noticed the discrepancy.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
