### ISSUE TITLE
No control motion from screen or App after engaving firmware V2.0.8_H24_20220107_N

### ISSUE THREAD

**Issue by Watto2021** [makerbase-mks/MKS-DLC32#104]
I have the latest firmware for a Normal laser frame and 2.4" screen Firmware V2.0.8_H24_20220107_N.
When an engrave is complete there is no motion from the DLC32. Tried X + and X- also Y+ and Y- through the screen and the Android App.
I have to cycle the power to board to resume movement.

**Comment by abinoer** [comment]
@Watto2021 Is it the inability to move after carving?What was done before this happened?

**Comment by Watto2021** [comment]
yes after carving, it happens every time. It is a new build and has done since startup.

**Comment by abinoer** [comment]
@Watto2021 I have not reproduced the situation you said, have you tried to change a TF card?
