### ISSUE TITLE
Andriod App Air Assist Option

### ISSUE THREAD

**Issue by Watto2021** [makerbase-mks/MKS-DLC32#105]
Hi 
 Is it possible to add a Air Assist Button In the Android App? In the Parameter Settings screen below work speed and laser power would be ideal, and Check Box [On] would write M7 into output code when Laser is operating M3 and M9 when laser command M5 off ?

**Comment by makerbase-mks** [comment]
Thanks for advice, we will consider to add it to the next version.

**Comment by abinoer** [comment]
Have been added
