### ISSUE TITLE
Z button 

### ISSUE THREAD

**Issue by Yamilli31** [makerbase-mks/MKS-DLC32#107]
Is there the possibility of having a Z movement button on the TFT? With the laser firmware normal

**Comment by abinoer** [comment]
DLC32 does not support TFT

**Comment by serial-tintypist** [comment]
> DLC32 does not support TFT

Wow, that is a really helpful comment. I am sure they meant either TS24 or TS35 TFT screen. Anyway, I am also interested in learning when you plan on adding such a basic feature as Z axis control to the touchscreen.

**Comment by solawc** [comment]
@Yamilli31 I think the TFT you mentioned should refer to TS24 or TS35. Currently, DLC32 only supports these two screens. The interface of TS24 has Z-axis control, and TS35 will also update the interface to add Z-axis control.
