### ISSUE TITLE
5V Logic Level

### ISSUE THREAD

**Issue by n0tmad84** [makerbase-mks/MKS-DLC32#109]
Hello,

with external motor drivers (DM542T) the logic level of X_EN, Y_EN and Z_EN drops to 3.6V instead of the supposed 5V. They are just powering 3 optocouplers within the driver.

Board Version is V2.1.

**Comment by abinoer** [comment]
@n0tmad84 You can try common voltage anode connection, and use external voltage, the voltage should meet the requirements of the driver parameters

**Comment by abinoer** [comment]
@n0tmad84 You can try common voltage anode connection, and use external voltage, the voltage should meet the requirements of the driver parameters
