### ISSUE TITLE
MKS Armor protective shell Fan install

### ISSUE THREAD

**Issue by MrCHarley** [makerbase-mks/MKS-DLC32#110]
Where does one connect a cooling fan for drivers on the DLC32 v2.1?  I see 2, 2pin 12/24v power out on the board. Will utilising them not interfere with the laser, or does it require an external power source?

**Comment by abinoer** [comment]
The two 12/24V outputs are fixed, unaffected by the program and do not interfere with the laser. You can connect fans to these two ports, but make sure the total input current does not exceed 5V
