### ISSUE TITLE
MKS DLC32 resets / short circuits anytime both limit switches are reached

### ISSUE THREAD

**Issue by pjrezai** [makerbase-mks/MKS-DLC32#111]
Hi! I am a newbie, but I don't know why the board resets / short circuits anytime both limit switches are reached. Any help would be very appreciated! :) (They are Makerbot limit switches)

**Comment by makerbase-mks** [comment]
Maybe you should invert the level of the endstops

**Comment by pjrezai** [comment]
> Maybe you should invert the level of the endstops

Thanks for the feedback!! Unfortunately my electronics knowledge is near 0. How would I do that? Thanks!!

**Comment by pjrezai** [comment]
Is there any pictures of video I could see to make sure i'm installing it correctly so it doesn't short circuit? What do you mean by inverting them?

**Comment by abinoer** [comment]
@pjrezai Short circuit? I think your wires are connected backwards. If you are using a mechanical limit, do not connect the 5V on the limit interface to avoid a short circuit caused by the wrong connection

**Comment by pjrezai** [comment]
> @pjrezai Short circuit? I think your wires are connected backwards. If you are using a mechanical limit, do not connect the 5V on the limit interface to avoid a short circuit caused by the wrong connection

How do I not connect the 5V? Which one is that wire? Since all of them are connected by a pin connector

**Comment by pjrezai** [comment]
Here are a couple pictures
![IMG_1489](https://user-images.githubusercontent.com/13514362/151727771-2437c8db-16a5-47bc-987a-8fa515ca04b2.jpeg)
![IMG_1488](https://user-images.githubusercontent.com/13514362/151727773-56febf18-42e9-41c6-b36a-579fb68aa1e1.jpeg)

**Comment by pjrezai** [comment]
Any help would be appreciated! :)

**Comment by abinoer** [comment]
There is screen printing on the motherboard, the red line on your picture is connected to 5V, you can pick out the red line
