### ISSUE TITLE
z axis on laser

### ISSUE THREAD

**Issue by kdaffy** [makerbase-mks/MKS-DLC32#112]
Hi, i tried to use the z axis with my laser (i want to use the rotary attachment on z axis of lightburn) but i can't make it work. The stepper motor i attached to z axis pin doesn't work. Do i have to flash another fw. Now i have the latest(V2.0.8_H35_20220105_N) for TS35/laser/normal/Board_V2.0. Thanks!!!

**Comment by kdaffy** [comment]
Sorry but it was my fault as there is no driver on z axis. I totally forgot it.

**Comment by kdaffy** [comment]
it was my mistake. I used a stepper driver and everything is ok

**Comment by Valachian** [comment]
Hi, did you managed to get it running ? i am thinking of similar setup, was there any firmware update necessary ?
