### ISSUE TITLE
Tmc 2209

### ISSUE THREAD

**Issue by kdaffy** [makerbase-mks/MKS-DLC32#113]
Hi. Can I use tmc 2209 drivers with my board? Do i have to do something or I just take out the a4988 and put the new ones?thanks

**Comment by Plottmania** [comment]
No problem, I use TMC 2208 and TMC 2209

**Comment by kdaffy** [comment]
I ask this because i have read somewhere that you have to swap the 2209 in comparison with the 4988.

**Comment by Plottmania** [comment]
I have among other things a Sculpfun with a MKS DLC32 and there run at the DLC32 V1.0 my TMC 2208 and at the DLC32 V2.0 my TMC 2209
When plugging on the right direction pay attention!
![IMG_20220103_151519229](https://user-images.githubusercontent.com/82659592/150758654-c1a2f66b-f07b-461c-a8e5-dc46f9e56c17.jpg)

**Comment by Devil-67** [comment]
which are the right ones ?
there are 2209 V1.2 V2.0 V3 V3.1

**Comment by torenich** [comment]
> which are the right ones ?

I dont think it matters what hardware rev, but you must use the step/dir, also known as legacy, or stand alone version. You cannot use the SPI or UART versions.

**Comment by kdaffy** [comment]
Hi, yesterday i received my tcm2209 from makerbase shop. I changed my old a4988 and changed the extended settingd $160, $161 and $162 from 16 to 256 (microsteps). They are very quiet but during an engraving suddenly it stopped engraving and i couldn't control the laser so i turned it off and on again. Does someone knows if when i change drivers i have to make any other settings? Thanks!!!

**Comment by Devil-67** [comment]
which 2209 did you take ?
There are different versions 1,2 - 3,0 ?
