### ISSUE TITLE
J3 - Switch

### ISSUE THREAD

**Issue by Plottmania** [makerbase-mks/MKS-DLC32#114]
A small question...
What is the Switch J3 for?

![MKS_DLC32_J3](https://user-images.githubusercontent.com/82659592/150756463-fcb3a086-bf84-4db2-9dde-db1f508470c7.JPG)

THX

**Comment by kdaffy** [comment]
you use it if you want to add a switch to the board to switch it on and off. if altough do this you have to remove the red fuse beside the switc
![Στιγμιότυπο οθόνης 2022-01-24 113602](https://user-images.githubusercontent.com/34399064/150757801-c923ef6f-57c1-4483-8b6a-1dc438a53fec.png)
h

**Comment by deltazerorsan** [comment]
It's an external power switch, but you must remove de fuse... And put one
also external.

**Comment by abinoer** [comment]
@Plottmania You can read the manual to understand the functions of various [interfaces[](url)][https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf](url)
