### ISSUE TITLE
laser firmware Z buttons and posibility change icons and buttons 

### ISSUE THREAD

**Issue by johnrodrit** [makerbase-mks/MKS-DLC32#116]
i have a k40 laser and need use the Z buttons, and change initial boot background, other issue is spanish pack lenguage

**Comment by abinoer** [comment]
We will add z-axis to future laser firmware

**Comment by abinoer** [comment]
We will try as soon as possible. Please be patient

**Comment by cfox1028** [comment]
> We will try as soon as possible. Please be patient

How much longer are we expected to wait?
This board would be so much more popular if it moved to open source already.

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
