### ISSUE TITLE
I guess I'll add my enclosure here too 😄 

### ISSUE THREAD

**Issue by torenich** [makerbase-mks/MKS-DLC32#117]
I made this enclosure for the DLC32 v2 with the TS24 screen.

https://www.prusaprinters.org/prints/110423-enclosure-for-mks-dlc32-v21-with-ts24-r-v20
<img width="170" alt="20220101_174133" src="https://user-images.githubusercontent.com/87596589/150902480-b5d3cde3-9dce-4c58-b4a4-31a0c9562c4b.png">

**Comment by abinoer** [comment]
Thank you for sharing
