### ISSUE TITLE
 No answer for months - so I write it as a new issue

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#118]
Could someone of MKS help me? @abinoer @solawc @makerbase-mks @mks-viva @MS1987

[Manual movements over LCD very fast](https://github.com/makerbase-mks/MKS-DLC32/issues/16#issuecomment-1021591553)

**Comment by trashypopashy** [comment]
Could please @makerbase-mks or @mks-viva of @MS1987 or @solawc or @abinoer or anyone else from Makerbase help me?

**Comment by trashypopashy** [comment]
Where is the support gone? @abinoer @solawc

**Comment by trashypopashy** [comment]
Again no support? What's wrong, MKS?

**Comment by abinoer** [comment]
Sorry, we don't have the energy to modify the independent firmware for each DIY client. The firmware has been open source and can be modified by ourselves
