### ISSUE TITLE
Laser and CNC on the same machine

### ISSUE THREAD

**Issue by serper** [makerbase-mks/MKS-DLC32#119]
I have built a machine with laser and dremel together, how should I use it as a cnc to make pcb and laser for engraving? I see that there are two different firmwares but I would need to be able to put laser or cnc mode depending on the moment.

**Comment by Juergen-Matthias** [comment]
I also run a laser and spindle on the same machine. Is there already a solution here or do I always have to change the firmware when changing tools?

**Comment by abinoer** [comment]
Sorry, only firmware can be replaced in this case
