### ISSUE TITLE
How to turn on WIFI via cmd?

### ISSUE THREAD

**Issue by automics** [makerbase-mks/MKS-DLC32#12]
Hi, I have no touch display, how to enable WiFi through the console?
> $I
[VER:1.1.2021051202:]
[OPT:PHSW]
[MSG:Using machine:MKS DLC32]
[MSG:No Wifi]

**Comment by JuananBluenoa** [comment]
[https://github.com/bdring/Grbl_Esp32/wiki/Settings](https://github.com/bdring/Grbl_Esp32/wiki/Settings)

**Comment by derFrickler** [comment]
Are you sure?
Guess it's not running grbl_esp32

**Comment by automics** [comment]
[ESP115] - Turns the WiFi ON or OFF

No connection, why is SSID not displayed?
$I
[VER:1.1.2021051202:]
[OPT:PHSW]
[MSG:Using machine:MKS DLC32]
[MSG:Mode=STA:SSID=:Status=Not connected:IP=0.0.0.0:MAC=7C-87-CE-12-9B-A8]
ok

**Comment by JuananBluenoa** [comment]
to connect to an access point (STA mode)
$ESP100=YOUR_SSID     or     $Sta/SSID=YOUR_SSID
to create an access point (AP mode)
$ESP105=newssid     or     $Ap/SSID=newssid

**Comment by automics** [comment]
After the reset, the connection was established!

[ESP444]RESTART
...
[ESP115]ON
[MSG:Client Started]
[MSG:Connecting winet]
[MSG:Connecting.]
[MSG:Connecting..]
[MSG:Connecting...]
[MSG:Connecting....]
[MSG:Connecting.]
[MSG:Connecting..]
[MSG:Connecting...]
[MSG:Connecting....]
[MSG:Connected with 172.16.0.41]
[MSG:Start mDNS with hostname:http://grblesp.local/]
[MSG:SSDP Started]
[MSG:HTTP Started]
[MSG:TELNET Started 23]
ok
WebUI connected!

**Comment by ahmetbozaci** [comment]
@automics Hello ı dnt have tft too. How did you open wifi. I check the this [page ](https://github.com/bdring/Grbl_Esp32/wiki/Settings) I try some codes but ı cant see board wifi in wifi list. I appreciate if you write how did you do that.

**Comment by ahmetbozaci** [comment]
> @automics Hello ı dnt have tft too. How did you open wifi. I check the this [page ](https://github.com/bdring/Grbl_Esp32/wiki/Settings) I try some codes but ı cant see board wifi in wifi list. I appreciate if you write how did you do that. ![image](https://user-images.githubusercontent.com/38635158/141522869-4626b927-73f4-4fc5-ab28-71c13abf0452.png)

I connect finally.If somebody cant connect

```
1. $ESP444=RESTART
2. $ESP115=ON  
3. $ESP100=your_ssdi_name
4. $ESP101=your_ssdi_password
5. $ESP110=STA
6. $ESP444=RESTART 
7. $ESP115=ON
```

Maybe it can work after step 5 but for me ı have to restart. Then open wifi you will see ip address in grbl console.

**Comment by SultanRR** [comment]
У меня аналогичная проблема , но проблемы подключения в wifi  нет . есть и дисплей , но после каждой перезагрузки MKS DLC32 нужно снова вручную подключаться к wifi , то есть я не могу отключить дисплей и удалено управлять станком , он сам не подключится к последней сети . проблема появилась после того как установил FluidNC , но он мне не понравился и решил установить родную прошивку ( DLC32_Laser_v2.2_2023120602 ) пробовал и другие прошивки но проблему не решает это
