### ISSUE TITLE
Web UI Sources

### ISSUE THREAD

**Issue by lgm42** [makerbase-mks/MKS-DLC32#121]
I would like to customize for my specific printer the web ui.
Are source available ?
I found ESP3D-WebUI (https://github.com/luc-github/ESP3D-WEBUI) which seems to be the base of the web ui. Do you use it as is or did you customize it to make it work for the MKS DLC32 ?

**Comment by solawc** [comment]
@lgm42 Yes, it is indeed based on it. You can use it directly, or you can make DIY modifications based on it, and then update it to the motherboard. This is all allowed, and the relevant protocols are basically the same.
