### ISSUE TITLE
M117 Command on web UI

### ISSUE THREAD

**Issue by lgm42** [makerbase-mks/MKS-DLC32#122]
I would like to know if it is possible to see M177 LCD message on Web UI ?
https://marlinfw.org/docs/gcode/M117.html

**Comment by torenich** [comment]
M117 looks like a Marlin specific command. These boards run Grbl.

**Comment by lgm42** [comment]
Yes I have understand if now ... I have spoken with ESP3D GUI main developper. We'll see together how to make that.
Thanks
