### ISSUE TITLE
Z axis steper driver is HOT

### ISSUE THREAD

**Issue by koszokradziej** [makerbase-mks/MKS-DLC32#124]
I have problem with Z axis in my laser. Motor doesn't move and the steper driver is very hot eaven if the motor is unplug. I replaced the steper driver with a another one but the problem is the same (steper driver is OK). So i think the problem is in the motherboard.

Can you help me?

**Comment by torenich** [comment]
You might want to check the current setting on your drivers. It sounds like it is set to high.

**Comment by koszokradziej** [comment]
Every driver set on the same value (0,7V on resistor) but problem are only with z axis

**Comment by makerbase-mks** [comment]
@koszokradziej Can you provide a image of your connection of the board?

**Comment by solawc** [comment]
@koszokradziej After you connect the Z axis, is the Z axis always in a locked state? And when the X/Y axis is unlocked, is it still locked?

**Comment by koszokradziej** [comment]
@solawc Yes

**Comment by abinoer** [comment]
Try to change to a good motor drive, if there is still this problem, there may be hardware damage
