### ISSUE TITLE
Running mobile app with DLC32

### ISSUE THREAD

**Issue by daven78** [makerbase-mks/MKS-DLC32#128]
Hello,
Some of the buttons in the mobile app don't display correctly on my iphone.  The formatting isn't correct.  Is this an issue you are aware of and correcting?  See attached picture
![mks lser](https://user-images.githubusercontent.com/12862166/153260319-6b373a9f-c5d6-4b1d-8965-aefeb5ed2026.PNG)
.

**Comment by abinoer** [comment]
@daven78 What kind of iPhone do you have and what is the system version numbe?

**Comment by serial-tintypist** [comment]
> @daven78 What kind of iPhone do you have and what is the system version numbe?

It looks exactly the same on my iPhone X, iOS version 14.7.1)

**Comment by daven78** [comment]
Iphone 11

Software version 15.1


________________________________

**Comment by daven78** [comment]
i fixed it by changing the language to Chinese then back to english and it fixed it.  Must be a bug in the language conversion routine.

**Comment by abinoer** [comment]
@daven78 Thanks for your feedback and we will fix it
