### ISSUE TITLE
Clone Y axis

### ISSUE THREAD

**Issue by Lazarus-Rising** [makerbase-mks/MKS-DLC32#13]
Hi, I need to be able to clone the Y axis as I need two stepper drivers for the two motors on the Y axis.
Could you post the source code please so I can achieve this?

**Comment by makerbase-mks** [comment]
Duplicate of #10

**Comment by Plottmania** [comment]
you can use the adapter from Barton and do not need a code.
Remember that the second axis is cloned and therefore mirror-inverted.

![DLC_Stepper_Out](https://user-images.githubusercontent.com/82659592/142801315-af725b6c-f6cf-4c81-9a9e-1decb2fa51eb.jpg)
