### ISSUE TITLE
MKS DLC32 TS35 SCREEN

### ISSUE THREAD

**Issue by PEACE-CNC** [makerbase-mks/MKS-DLC32#131]
Can PROBE feature be added to TS 35 CNC screen?

**Comment by makerbase-mks** [comment]
It supports the probe on board, you mean adding something display on LCD?

**Comment by abinoer** [comment]
@PEACE-CNC Thank you for your feedback and we will add it in the next future update

**Comment by solawc** [comment]
Please update the new firmware
