### ISSUE TITLE
Editing configuration.h file

### ISSUE THREAD

**Issue by kdaffy** [makerbase-mks/MKS-DLC32#132]
Hi, is it possible to edit the configuration.h file and where could i find it? The firmware files are ''bin'' files. Does anyone know how can i do this? In my 3d printer i easilly do it with ''arduino ide'' or ''visual studio code''. Here how do we edit it????Thanks!!!!

**Comment by makerbase-mks** [comment]
Can this help you?https://github.com/makerbase-mks/MKS-DLC32/wiki/Firmware#configure-through-configuration-files

**Comment by kdaffy** [comment]
Thanks but i already know this. This is the basic configuration. I need the configuration.h file which has all the settings as for example what stepper drivers you use or the configuration of limit switches and a many many more as we do in a 3d printer. Thanks!!!
See this example :  https://marlinfw.org/docs/configuration/configuration.html

**Comment by torenich** [comment]
@kdaffy 

These boards do not run Marlin. They run a version of Grbl for ESP32. A full list of settings can be found here...
https://github.com/bdring/Grbl_Esp32/wiki/Settings

Pretty much any setting you need to change can be done with extended settings form the console.

This is currently the only was to change settings until MKS releases the source.

**Comment by kdaffy** [comment]
Thank you very much. This is what i wanted!!!!!

**Comment by josmeijer** [comment]
What I miss here is the configuring through the web interface 
![settings wifi](https://github.com/user-attachments/assets/c61b9bd6-9067-4768-b3d1-2cb3db770bdd)

**Comment by josmeijer** [comment]
![settings](https://github.com/user-attachments/assets/21cc60ca-466f-441f-98eb-3fc0139fbe69)
