### ISSUE TITLE
Will there be open-source firmware?

### ISSUE THREAD

**Issue by maxholgasson** [makerbase-mks/MKS-DLC32#146]
Will there be open-source firmware so that you can edit the screen as you wish etc?

**Comment by giordy72** [comment]
+1 for code release

**Comment by IvanPotapow** [comment]
+1

**Comment by AngleV** [comment]
+1

**Comment by serial-tintypist** [comment]
+100

**Comment by daxliniere** [comment]
Yes, we could also submit pull requests here.

**Comment by Gabri988** [comment]
+1

**Comment by simulz** [comment]
source code가 필요합니다.
다른 용도로 사용하기 위해 새로 만들고 싶습니다.
Pin map이라도 알려주세요.

**Comment by daxliniere** [comment]
@simulz, I think the pin map is already released, but not the source code, so we are unable to add things like true emergency stop button (not just reset ESP32) or add extra buttons to the GUI.

**Comment by simulz** [comment]
@daxliniere Could you tell me where the pin map is? I can't find it here.
If you have MKS DLC32 ESP32 pin map, I can program it.

**Comment by daxliniere** [comment]
@simulz have a look here: https://github.com/makerbase-mks/MKS-DLC32/tree/main/hardware

Specifically https://github.com/makerbase-mks/MKS-DLC32/blob/main/hardware/MKS%20DLC32%20V2.1_003/MKS%20DLC32%20V2.1_003%20SCH.pdf

**Comment by daxliniere** [comment]
At the bare minimum, the Buzzer pin could be repurposed for something more important like a true emergency stop button. (In case you are not aware, using the existing emergency stop function just PUSHES reset on the ESP-32.)

**Comment by CLP58** [comment]
+10000

**Comment by geogarden** [comment]
+1000. When ?

**Comment by MTRatcliffe** [comment]
+1

**Comment by ubergeekseven** [comment]
I am trying to move to fluidnc since this project is just a stolen version of esp32grbl. Trying to figure out pin mapping still though.

**Comment by ubergeekseven** [comment]
What is the ttl pin gpio?

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
