### ISSUE TITLE
tmc2209 issue

### ISSUE THREAD

**Issue by kdaffy** [makerbase-mks/MKS-DLC32#149]
Hi, yesterday i received my tcm2209 from makerbase shop. I changed my old a4988 and changed the extended settingd $160, $161 and $162 from 16 to 256 (microsteps). They are very quiet but during an engraving suddenly it stopped engraving and i couldn't control the laser so i turned it off and on again. Does someone knows if when i change drivers i have to make any other settings? Thanks!!!

**Comment by torenich** [comment]
That isn't going to work. I believe those microstep settings ($160-$162) are for UART or SPI drivers which the DLC32 doesn't support. If you have the standalone 2209s the highest you can set them for is 64 microsteps (according to the tables you referenced, but I've only seen them set to a max of 16) via the dip switch. If you set them for 16, the drivers interpolate this into 256 steps internally.

**Comment by abinoer** [comment]
Yes,set them for 16, the drivers interpolate this into 256 steps internally.

**Comment by Devil-67** [comment]
How is switch M2 set on the 2209 ?
It is not indicated in the table
![Unbenannt](https://user-images.githubusercontent.com/31169133/156918215-903af941-723d-4a8c-9368-6e1725e81590.PNG)
.

**Comment by abinoer** [comment]
@Devil-67 M2 is not indicated, indicating that M2 is ignored, and M2 high and low low are the same  @Devil-67
