### ISSUE TITLE
Z PROBE PROBLEM

### ISSUE THREAD

**Issue by PEACE-CNC** [makerbase-mks/MKS-DLC32#152]
Hi, when Z Probe is used in programs, it crashes. Z probe latest version is not available. I have sent the relevant pictures
![001](https://user-images.githubusercontent.com/78286508/156926129-1c458828-3027-4860-a4fc-9cf088c5103b.png)
![002](https://user-images.githubusercontent.com/78286508/156926136-c6dc54dd-4ac0-4ed8-9c81-5806ab8426ee.png)
![003](https://user-images.githubusercontent.com/78286508/156926140-0f44a4b2-5401-4058-a228-005e252c6471.png)
![004](https://user-images.githubusercontent.com/78286508/156926144-88ecd111-6128-4770-95b6-69c569bdd738.png)
.

**Comment by abinoer** [comment]
Which firmware are you using? Can the probe function on candle be used normally

**Comment by abinoer** [comment]
Set $6 to 1, this function can be restored to normal
