### ISSUE TITLE
Controllerboard restarts.

### ISSUE THREAD

**Issue by gibetnicht** [makerbase-mks/MKS-DLC32#153]
This is only a question. Is it normal, that the Controllerboard restarts, after pluging it to the PC?

**Comment by manuelchaves** [comment]
hi, it shouldn't but it happens and with several others, as it also resets or crashes when disconnecting

**Comment by abinoer** [comment]
@gibetnicht Do you mean the board reboots the first time you click "connect"? If so, that's normal
