### ISSUE TITLE
MKS DLC32 CNC FİRMWARE BEEPER

### ISSUE THREAD

**Issue by PEACE-CNC** [makerbase-mks/MKS-DLC32#156]
Hi, I would be happy if the beep feature can be added to the latest firmware as a CNC. Because the Laser has it in the firmware. Thanks.

**Comment by abinoer** [comment]
Thanks for your feedback, this will be added in the future version

**Comment by daxliniere** [comment]
What is the beeper feature?

**Comment by kweilim98** [comment]
When the firmware CNC will updated? Why the beeper not function when the limit switch is on?

**Comment by abinoer** [comment]
> Hi, I would be happy if the beep feature can be added to the latest firmware as a CNC. Because the Laser has it in the firmware. Thanks.

Fixed, please update firmware

**Comment by burak1000** [comment]
i dont understand how can i beep via gcodes ? from my file ?

**Comment by clodo1977** [comment]
qual comando devo incluir no inicio do g-code, para acionar o bip antes do inicio do trabalho
