### ISSUE TITLE
Manual movements over LCD very fast

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#16]
My CNC-machine has all the axles driven by leadscrew. So I have to configure the steps/mm to 800. When I do this, the manual movements on the LCD-Screen are extremely fast. It is only possible to move with low setting on the LCD-menu. Moving with high or mid, my CNC tries to drive way too fast and is loosing most of the movements steps. The homing-speeds which are configured in dlc_cfg.txt do not influence these manual movements in the LCD-menu.

Could you please make a dependency between these speeds an the steps/mm? Maybe it is just the accelleration that is too high, but even the max accelleration in dlc_cfg.txt does not affect these moves.

**Comment by solawc** [comment]
> The movements which I type in a gCode-File or in the console are done correctly. But the moves that are done with the control-panel on the LCD are VERY FAST (in "Low Speed" it is already fast, but my CNC can handle it), when I set the steps/mm from 80 to 800 (which I need for my leadsrewcs).

If you can upload a control video, I can better understand the phenomenon; I don't have a good concept of the speed I say to you, because I set a fixed value

**Comment by trashypopashy** [comment]
I would prefer something in between... maybe the feedrates for manual moves on the LCD can be influenced in the $yx-settings in the dlc_cfg.txt.

**Comment by solawc** [comment]
> @solawc Do You have an idea, how to solve this problem?

The moving speed is a fixed speed in the firmware, and the pulse setting has nothing to do with this speed. In terms of configuration, low speed is 500, medium speed is 1000, and high speed is 2000

**Comment by Plottmania** [comment]
No matter how you do it but with 17 steppers and these spindles the maximum speed is around 1300 mm / min
I have tried a lot but 2000 mm / min is absolutely too fast.
I know the problem and has also the 3018 and Co.

They can't set speed records...and I would have set 1000 mm / min as the maximum speed.
A fast controller does not make a fast machine : )

**Comment by trashypopashy** [comment]
> > @solawc Do You have an idea, how to solve this problem?
> 
> The moving speed is a fixed speed in the firmware, and the pulse setting has nothing to do with this speed. In terms of configuration, low speed is 500, medium speed is 1000, and high speed is 2000

Could you please make half the speeds for me? So I need a CNC normal firmware with half the LCD-moved speeds fir a V1.1-Biard.

**Comment by Plottmania** [comment]
You can set this yourself.

$110=1000.000 
$111=1000.000 
$112=200.000 

No need to change the firmware!

**Comment by trashypopashy** [comment]
No, this doesn't change it for the LCD-input movements.

**Comment by trashypopashy** [comment]
> > > @solawc Do You have an idea, how to solve this problem?
> > 
> > 
> > The moving speed is a fixed speed in the firmware, and the pulse setting has nothing to do with this speed. In terms of configuration, low speed is 500, medium speed is 1000, and high speed is 2000
> 
> Could you please make half the speeds for me? So I need a CNC normal firmware with half the LCD-moved speeds for a V1.1-Board.

@solawc please make a special firmware for me... or go open source.

**Comment by trashypopashy** [comment]
> > Could you please make half the speeds for me? So I need a CNC normal firmware with half the LCD-moved speeds for a V1.1-Board.
> 
> @solawc please make a special firmware for me... or go open source.

@solawc @makerbase-mks @mks-viva @MS1987 when can I get an update? And please go open source!

**Comment by makerbase-mks** [comment]
@trashypopashy Would update to you today.

**Comment by makerbase-mks** [comment]
[V2.0.4_H35_S_20211206_N_CNC.bin.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7658589/V2.0.4_H35_S_20211206_N_CNC.bin.zip)
Please check it.

**Comment by trashypopashy** [comment]
@makerbase-mks is this with
Fix the problem that $1=255 cannot be locked

Fix the problem that after some pop-up windows appear, they can't pop up in the follow-up

Fix the problem of Z zero return error

Fix the problem that the default value is not restored when re-sculpting after adjusting FeedOverride/SpindleSpeedOverride during engraving
Fix automatic WiFi reconnect
?

Which Board version is it for (V1 or V2)?

**Comment by trashypopashy** [comment]
So You halfed the LCD-Speeds. Fine, but WiFi-reconnect still does not work.

**Comment by trashypopashy** [comment]
@makerbase-mks or @solawc could You please give me a halfed-LCD-speed-Version if the MKS-DLC32/firmware/TS35/CNC/Normal/Board_V1.0/V2.0.7_H35_20211213_N_CNC.bin?

**Comment by solawc** [comment]
> So You halfed the LCD-Speeds. Fine, but WiFi-reconnect still does not work.

Did you mean that the wifi automatic connection does not work?

**Comment by solawc** [comment]
> @makerbase-mks or @solawc could You please give me a halfed-LCD-speed-Version if the MKS-DLC32/firmware/TS35/CNC/Normal/Board_V1.0/V2.0.7_H35_20211213_N_CNC.bin?

Yes, but I’m a bit busy today. I will configure a special CNC firmware for you tomorrow to reduce the speed of the screen control movement. Is it the same as the previous one?

**Comment by trashypopashy** [comment]
> > So You halfed the LCD-Speeds. Fine, but WiFi-reconnect still does not work.
> 
> Did you mean that the wifi automatic connection does not work?
Yes, this did not work.

**Comment by trashypopashy** [comment]
> > @makerbase-mks or @solawc could You please give me a halfed-LCD-speed-Version if the MKS-DLC32/firmware/TS35/CNC/Normal/Board_V1.0/V2.0.7_H35_20211213_N_CNC.bin?
> 
> Yes, but I’m a bit busy today. I will configure a special CNC firmware for you tomorrow to reduce the speed of the screen control movement. Is it the same as the previous one?

TS35, CNC, Normal, Board V1.0, halfed-LCD-speed-Version

**Comment by trashypopashy** [comment]
> > > @makerbase-mks or @solawc could You please give me a halfed-LCD-speed-Version if the MKS-DLC32/firmware/TS35/CNC/Normal/Board_V1.0/V2.0.7_H35_20211213_N_CNC.bin?
> > 
> > 
> > Yes, but I’m a bit busy today. **I will configure a special CNC firmware for you tomorrow** to reduce the speed of the screen control movement. Is it the same as the previous one?
> 
> TS35, CNC, Normal, Board V1.0, halfed-LCD-speed-Version

I hope, You did not forget me @solawc

**Comment by solawc** [comment]
[V2.0.7_H35_20211217_N_CNC_S.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7731503/V2.0.7_H35_20211217_N_CNC_S.zip)
@trashypopashy

**Comment by solawc** [comment]
Sorry, I was a little busy these two days, but I didn’t forget @trashypopashy

**Comment by trashypopashy** [comment]
> [V2.0.4_H35_S_20211206_N_CNC.bin.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7658589/V2.0.4_H35_S_20211206_N_CNC.bin.zip) Please check it.

> [V2.0.7_H35_20211217_N_CNC_S.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7731503/V2.0.7_H35_20211217_N_CNC_S.zip) @trashypopashy

@solawc automatic WiFi-reconnect works now with firmware V2.0.7 on my V1-Board, BUT again the dlc_cfg.txt-uplads fails (as here: [)](https://github.com/makerbase-mks/MKS-DLC32/issues/35)

**Comment by trashypopashy** [comment]
> > [V2.0.4_H35_S_20211206_N_CNC.bin.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7658589/V2.0.4_H35_S_20211206_N_CNC.bin.zip) Please check it.
> 
> > [V2.0.7_H35_20211217_N_CNC_S.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7731503/V2.0.7_H35_20211217_N_CNC_S.zip) @trashypopashy
> 
> @solawc automatic WiFi-reconnect works now with firmware V2.0.7 on my V1-Board, BUT again the dlc_cfg.txt-uplads fails with Your special-version v2.0.4 and v2.0.7 (as [here](https://github.com/makerbase-mks/MKS-DLC32/issues/35)
> 
> I tried with and without added $133, $134 and $135. It does not finish the upload.

@solawc Even with Your lastest firmware V2.0.8 it is not possible to update the configuration with the dlc_cfg.txt

**Comment by trashypopashy** [comment]
@mks-viva @MS1987 @makerbase-mks @solawc could you please help me? Maybe you can again provide a special version of the latest firmware for CNC normal with 35TFT Board V1 an halved LCD-speeds, bit this time updateable with the config-file over sd-card.

**Comment by trashypopashy** [comment]
@abinoer could You please take care of a firmware with my wishes above (latest firmware for CNC normal with 35TFT Board V1 an halved LCD-speeds)?

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
