### ISSUE TITLE
EASEL SOFTWARE

### ISSUE THREAD

**Issue by PEACE-CNC** [makerbase-mks/MKS-DLC32#160]
MKS DLC32 does not communicate with ESAEL software.

**Comment by abinoer** [comment]
Software that supports GRBL firmware is ok

**Comment by darktempl** [comment]
Hello. I'm probably off topic. installed the latest CNC firmware. did not find the command to reboot the controller, please tell me. There is a problem when I close the contact, the screen goes blank and does not turn on, is it in the firmware?

**Comment by abinoer** [comment]
@darktempl close the contact?Where did you close?I have no idea what you mean

**Comment by darktempl** [comment]
Reset contact closes the screen goes out and does not turn on.
![1](https://user-images.githubusercontent.com/72755941/159113261-1da32241-4653-42de-8a3e-c9cc68c34f48.jpg)

**Comment by abinoer** [comment]
Are you closed all the time?This is the reset interface and can be used as an emergency stop. Keep closed will always reset, the screen will not display normally

**Comment by darktempl** [comment]
is it possible to reboot the board? without a power outage?

**Comment by abinoer** [comment]
Yes, if you close it and disconnect it, you restart it

**Comment by darktempl** [comment]
reboot the board remotely will not work with some command?

**Comment by abinoer** [comment]
The command can be sent normally after the restart.What's going on there, I don't understand

**Comment by andrewnzsouth** [comment]
Hi is there a fix for easel software to work with the dlc32 v2.1 yet ? 
im have no luck Connecting 
Cheers

**Comment by Freir1771** [comment]
Hi
I just bought a ttc450, with an MKS-dcl32 v2.1. 
Found a new firmware version on twotrees site, and instaled it since release-letter says it supported easel. Tried it out and that was it works (at least for windows, no luck with ubuntu)

Her is the site wher i  
OBS: After firmware update i had to sett up the configuration file

**Comment by snbuch** [comment]
> Hi I just bought a ttc450, with an MKS-dcl32 v2.1. Found a new firmware version on twotrees site, and instaled it since the release-letter says it supported easel. Tried it out and it works (at least for windows, no luck with ubuntu)
> 
> Her is the site where i downloadet it from. https://www.twotrees3dofficial.com/pages/twotrees-download OBS: After firmware update i had to sett up the configuration file. The MKS lasertool, dit not work for uploading the configuratin tool. So I had to use USG an manualy enter the settings.
> 
> Hope this help Edit: that's said, the connection is not stable, multiple of my jobs has ended randomly before it's actually finished. It also seems that having my computer connectedto the cnc wile runing my jobs from the sc-card, disturb the job, since it also prematurely end the jobb. Gues i have to try another cable.
> 
> (When my computer is disconnectet completely it working just fine when running from the SD card)

Thanks for sharing this link. Seems this firmware works for the 3018 Pro as well. The only issue is that the TS24 display does not work with this version.
