### ISSUE TITLE
number of copies on TS35 not working properly

### ISSUE THREAD

**Issue by serial-tintypist** [makerbase-mks/MKS-DLC32#162]
MKS DLC32 v2.1, normal laser mode with a TS35 screen. When I upload a gcode file to the SD card and then run it from the TS35 screen, I can set the number of copies of the job. However, there is no pause between the individual runs, the laser finishes one copy and then runs another copy right away. There is no way to switch workpieces between copies this way, it works as multiple passes on the same workpiece instead (which makes no sense as you set the number of passes in software that creates the gcode in advance). Please add functionality that will pause the laser and wait for user confirmation between copies.

**Comment by abinoer** [comment]
This is the same logic as software GRB to set the number of engraving.

**Comment by abinoer** [comment]
![1647919125(1)](https://user-images.githubusercontent.com/96047125/159401159-16364d66-0ef0-4e7c-ade8-b07428535bad.jpg)
Sorry, not GRB, but GRBL，LaserGRBL
