### ISSUE TITLE
Please add continuous jogging to TS24 and TS35

### ISSUE THREAD

**Issue by serial-tintypist** [makerbase-mks/MKS-DLC32#163]
It would be of great help for larger machines if the touch screen also allowed for the laser tool to be jogged continuously instead of having to press the jog arrows over and over again. Maybe add a toggle switch to the control screen just like in Lightburn? 

![Screenshot 2022-03-16 at 14 46 13](https://user-images.githubusercontent.com/98537930/158604082-1b9fb299-d4d3-4d97-96ba-5051e31e8d4a.png)

Thank you.

**Comment by manuelchaves** [comment]
Good

**Comment by daxliniere** [comment]
Yes, this would be great,

**Comment by abinoer** [comment]
I'm very sorry. After review, we considered various factors, such as the possibility of crash, so we decided to keep it unchanged

**Comment by serial-tintypist** [comment]
On the contrary, I keep crashing the laser tool when trying to jog it by touching the arrows a hudred times.
