### ISSUE TITLE
CNC Firmware Z-Homing doesn't work

### ISSUE THREAD

**Issue by christian-hellwig** [makerbase-mks/MKS-DLC32#164]
When I issue a $H command only x and y home. Manual control of z-axis and hard endstops work. Could you please add the option for homing z.

**Comment by christian-hellwig** [comment]
Hm that worked kind of. Now the z-endstop doesn't trigger

**Comment by abinoer** [comment]
Sorry, we forgot to specify this.
Turn on:  $Homing/Cycle1=Z
Turn off:  $Homing/Cycle1=0

**Comment by christian-hellwig** [comment]
Yeah the homing starts, but as mentioned the endstop doesn't work. Could it be, that the pin isn't assigned in the config?

**Comment by christian-hellwig** [comment]
Okay that seemed to be an error with an older firmware. Updated to the latest CNC Firmware and now the endstop is recognized as well. Thanks for the support

**Comment by abinoer** [comment]
Yes, the latest firmware I tried is ok

**Comment by daxliniere** [comment]
> Can you try this command in lasergrbl? 
>$Homing/Cycle0=XY
>$Homing/Cycle1=Z
> This mean that Homing cycle will be XY axis together and than Z axis

Thanks @Ondrashek.

The safer option would be to home the Z-axis first.

$Homing/Cycle0=Z
$Homing/Cycle1=XY

**Comment by Ondrashek** [comment]
> > Can you try this command in lasergrbl?
> > $Homing/Cycle0=XY
> > $Homing/Cycle1=Z
> > This mean that Homing cycle will be XY axis together and than Z axis
> 
> Thanks @Ondrashek.
> 
> The safer option would be to home the Z-axis first.
> 
> $Homing/Cycle0=Z $Homing/Cycle1=XY

For CNC sure. I am using XY first for laser :-)

**Comment by adilrs** [comment]
> > Can you try this command in lasergrbl?
> > $Homing/Cycle0=XY
> > $Homing/Cycle1=Z
> > This mean that Homing cycle will be XY axis together and than Z axis
> 
> Thanks @Ondrashek.
> 
> The safer option would be to home the Z-axis first.
> 
> $Homing/Cycle0=Z $Homing/Cycle1=XY

Salvou minha vida ! :-D   Estava tentando a 2 dias

**Comment by Hargard339** [comment]
Yea that works. Thank you.
