### ISSUE TITLE
Q: Can TS35 firmware run with TS24?

### ISSUE THREAD

**Issue by daxliniere** [makerbase-mks/MKS-DLC32#168]
I noticed that the menus for the TS35 seem more comprehesive (not to mention nicer colour scheme!) compared to the TS24.

Is it possible to run the TS35 firmware when TS24 screen is connected? I understand all UI elements will be smaller, of course.

All the best,
Dax.

**Comment by abinoer** [comment]
Sorry, you must use TS24 firmware to connect to TS24

**Comment by daxliniere** [comment]
Thanks for the prompt response, @abinoer! :)
