### ISSUE TITLE
MKS DLC 32 Limit Switch connection

### ISSUE THREAD

**Issue by idilbaz** [makerbase-mks/MKS-DLC32#171]
Hello, I will connect to my mks dlc 32 board with two limit switches on each axis. Is it okay if I make the connection as in the following figure?

![limit switch5](https://user-images.githubusercontent.com/102018170/159222916-5596534e-292a-445f-a284-d0fa50dda59c.jpg)

**Comment by serial-tintypist** [comment]
Unfortunately, these particular switches will not work when connected in parallel like this (I know this from experience with my setup). You need to disconnect the red (5 V) line and use signal and GND only.

**Comment by idilbaz** [comment]
In which way do I need to connect these shapes (A or B)
![A](https://user-images.githubusercontent.com/102018170/159419255-8d7285ea-7789-444b-99dd-3328ed1060c4.jpg)
![B](https://user-images.githubusercontent.com/102018170/159419265-fb5b5a42-da9e-488f-849c-d8466366b3ae.jpg)

**Comment by idilbaz** [comment]
> Unfortunately, these particular switches will not work when connected in parallel like this (I know this from experience with my setup). You need to disconnect the red (5 V) line and use signal and GND only.

In which way do I need to connect these shapes (A or B)

![A](https://user-images.githubusercontent.com/102018170/159419526-580992cc-7d4b-459c-a684-00d1daf4f523.jpg)
![B](https://user-images.githubusercontent.com/102018170/159419529-d867d11f-bd8c-4ddd-bfb0-82e0afa2a74a.jpg)

**Comment by serial-tintypist** [comment]
B (green is signal and black is GND)

**Comment by idilbaz** [comment]
> B (green is signal and black is GND)

Thank you so much :)

**Comment by kweilim98** [comment]
I try already  with as u say but when I touch the limit switch, why it delay to respond? And after that my touch screen panel restart again problem happen, how?

**Comment by idilbaz** [comment]
Hello, as you said, I made the connections as in figure B, but it does not work properly.  The Z axis limit switch does not work at all, and when the others touch the limit switch button, it gives an alarm in the UGS program, but it resets itself and starts the program again.  Why does the problem occur?  Did I make the connections wrong?

**Comment by idilbaz** [comment]
My problem is solved.  The problem is with these limit switches.  They are not suitable for CNC machine.  I just used a limit switch, everything seems fine now.

**Comment by kweilim98** [comment]
> My problem is solved. The problem is with these limit switches. They are not suitable for CNC machine. I just used a limit switch, everything seems fine now.

![Screenshot_2022-03-23-21-46-35-604_com android chrome](https://user-images.githubusercontent.com/66898187/160659126-f3ca79ec-9d35-4300-94ed-7d4e6492c1ff.jpg)

Bro, does u mean this limit switch module not suitable for the CNC?

**Comment by idilbaz** [comment]
> 

Yes my friend.  I used Arduino CNC Shield before, and these limit switches did not work.  These switches did not work on the MKS DLC 32 board either.

**Comment by mikaildogru** [comment]
hey friend how did you solve this probem?. I will plan door switch to connect sEmergency switches with series type ?. What do you think

**Comment by kweilim98** [comment]
> hey friend how did you solve this probem?. I will plan door switch to connect sEmergency switches with series type ?. What do you think

What kind switch you using?

**Comment by levent362727** [comment]
Merhaba ben mks dlc32 v2.1 kartim icin end stop kullanıyorum cihaz yeniden başlıyor neden oluyor bide gec algılıyor neden oluyor fikiri olan varmı
