### ISSUE TITLE
problema con probe e ugs

### ISSUE THREAD

**Issue by massimop3632** [makerbase-mks/MKS-DLC32#173]
buona sera, sto usando per la prima volta la board dlc32 v2,1 
ho provato a connettere la mia cnc a ugs
funziona tutto bene per ora ma provando a fare il ciclo di sondaggio mi va subito in allarme.
premetto che ho flashato il firmware tft35 cnc n
qualcuno può aiutarmi?

**Comment by abinoer** [comment]
I'm sorry, I don't understand. Could you be more specific? Preferably with pictures
