### ISSUE TITLE
homing asse z

### ISSUE THREAD

**Issue by massimop3632** [makerbase-mks/MKS-DLC32#174]
buona sera 
sto provando per la prima volta la dlc32 v2.1 su una fresa cnc.
ho impostato i parametri per homing ma l'asse z , si comporta come se fosse una macchina laser
ho caricato il firmware V2.0.8_H35_20220105_N_CNC
dove trovo il file config.h?

**Comment by abinoer** [comment]
Do you mean to use CNC firmware and then Z-Homing doesn't work?Z-homing can be configured by sending commands
![1648520065(1)](https://user-images.githubusercontent.com/96047125/160519069-b7daf096-432b-432b-85c3-16f3b7ee52b1.jpg)

**Comment by Gabri988** [comment]
@massimop3632 dalla console inserisci questa riga di comando: $Homing/Cycle1=Z e fai un homing

La macchina seguirà quest'ordine di azzeramento assi, XY e per ultimo Z. Non ho ben capito perché lo Z viene fatto per ultimo ma purtroppo è così 😅
