### ISSUE TITLE
G92 Z19.2 command problem

### ISSUE THREAD

**Issue by idilbaz** [makerbase-mks/MKS-DLC32#175]
Hello, I am using the UGS program. I made the Z probe connection to my MKS DLC 32 v2.0 card. The code g38.2 Z-10 F20 works. With this code, I can find the probe, but after finding the probe, the G92 Z19.2 command to go to the zero position does not work. Why might the problem occur?

**Comment by abinoer** [comment]
![1648777606(1)](https://user-images.githubusercontent.com/96047125/161178667-2ebd2909-7250-41e4-b1ae-a3c2a3d467f0.jpg)
Hello, my candle test is normal. What kind of host are you using

**Comment by idilbaz** [comment]
> ![1648777606(1)](https://user-images.githubusercontent.com/96047125/161178667-2ebd2909-7250-41e4-b1ae-a3c2a3d467f0.jpg) Hello, my candle test is normal. What kind of host are you using

Thank you for your answer.  I detected the problem.  While the Z axis is going down, the tooth is skipping, so it misses the zero point.  Now I'm going to refresh the z-axis.
