### ISSUE TITLE
Relay module on spindle port

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#178]
Does anyone have try to use this kind relay to control the spindle? Since I have connect and when I on my relay my whole current trick? Any information or detail on that? Since I m using the 600w bldc spindle
![IMG-20220401-WA0016](https://user-images.githubusercontent.com/66898187/161251198-162a4329-f711-437f-8639-507aea5bea14.jpg)
![IMG-20220302-WA0022](https://user-images.githubusercontent.com/66898187/161251208-1ccb15c2-01c1-4c3e-8af3-ddc0c98389c0.jpg)

**Comment by kweilim98** [comment]
Can request the spindle port from the motherboard become the pwm signal?

**Comment by abinoer** [comment]
Hello,  Spindle Port outputs a PWM signal

**Comment by kweilim98** [comment]
Ok
