### ISSUE TITLE
Limit pins invert issue

### ISSUE THREAD

**Issue by dhanninacs** [makerbase-mks/MKS-DLC32#179]
I have dual y axis stepper motors and two y limit switches on either side in Normally open position connected in series. So both switches need to trigger for hard limit to switch on. I'm using $5=1 to achieve this. 

But doing this, the x-limit switch which is also connected to Normally open and ground doesn't trigger when the limit switch is pushed. I have tried other limit switches to see if it is the problem but it looks like more of an $5 issues on board side. Did anyone have similar issues? I have a DLC 32 v2.1 board.

**Comment by abinoer** [comment]
I don't quite understand your description. Are you in a situation where Y-limit works and X-Limit doesn't? Is only one Y Limit Switches and one X Limit Switches restored? Can you upload wiring pictures

**Comment by dhanninacs** [comment]
Hi yes, when I have $5=1, and the X-axis limit switch connected to normally open position. The limit switch doesn't trigger when pushed.

**Comment by abinoer** [comment]
Short X limit interface S and GMD, can trigger? If so, there's something wrong with your limit switch

**Comment by dhanninacs** [comment]
I have tried other limit switches, they too don’t work. With $5=0 and limit switches connected in normally closed position everything works fine.

**Comment by dhanninacs** [comment]
It was a wiring issue. All sorted out now and works as intended. Thanks
