### ISSUE TITLE
no Z axis movement and unable to upload firmware

### ISSUE THREAD

**Issue by grumpyduck300** [makerbase-mks/MKS-DLC32#18]
controller will not move z axis on my machine and i keep getting a sync error when using the download tool. what can i do to fix this issue?

**Comment by solawc** [comment]
> controller will not move z axis on my machine and i keep getting a sync error when using the download tool. what can i do to fix this issue?

Yes, for the current firmware, since the limit return mode is not configured, the return mode is x, y return to zero, and there is no Z, so the Z axis is shielded temporarily. This will be issued and the return configuration mode will be provided at the next function version update; If there is a problem with your download, please provide feedback error information so that I can evaluate the problem

**Comment by derFrickler** [comment]
Try with a lower baud rate, hat problems flashing mine with 921600 as well.

**Comment by grumpyduck300** [comment]
Tried the lower baudrate same issue if there any jumpers on the board that need to be adjusted to put the board into download mode?

**Comment by killrob** [comment]
> 
> 
> I've had the same issue. I solved my problem like this: I needed not just to start the flashing tool with admin rights, but first change the files properties >> Security >> to "full control"

i still have full control on both files, the firmware and the .exe, and i ran it as admin but still same issue than @grumpyduck300 .
the only difference is that i run a newer version of the tool the 3.9.0

**Comment by rlinta** [comment]
I have a similar problem. the firmware does not load - sync error.

ch0 - io0 (esp32 pin 25)
ch1 - reset (esp32 pin 3)
ch2 - probe/io2 (esp32 pin 24)

![fw_load_io0 reset probe](https://user-images.githubusercontent.com/84626350/138118343-fa843e3e-1cd1-4c6c-9ca4-c5a414ccbe86.png)

![mks_esp32_download_tool](https://user-images.githubusercontent.com/84626350/138118545-d4baa90c-c405-452b-8413-36fd909be8e1.png)

**Comment by killrob** [comment]
> 
> 
> I have a similar problem. the firmware does not load - sync error.
> 
> ch0 - io0 (esp32 pin 25) ch1 - reset (esp32 pin 3) ch2 - probe/io2 (esp32 pin 24)
> 
> ![fw_load_io0 reset probe](https://user-images.githubusercontent.com/84626350/138118343-fa843e3e-1cd1-4c6c-9ca4-c5a414ccbe86.png)
> 
> ![mks_esp32_download_tool](https://user-images.githubusercontent.com/84626350/138118545-d4baa90c-c405-452b-8413-36fd909be8e1.png)

hi @rlinta , where do you found  the MKS ESP32 download tool?

**Comment by Lazarus-Rising** [comment]
so is this the definitive answer then to the lack of movement on the Z axis?
I've uploaded the cnc firmware but still no Z axis movement.
can MKS confirm the connecting the capacitor to gnd etc is correct and will Z axis movement then be enabled in laser mode?

**Comment by Anderson8153** [comment]
> este é o erro que recebo toda vez que tento fazer o upload do firmware cnc esperando que o z esteja habilitado
> 
> existe alguma maneira de fazer upload dos arquivos de configuração brutos para que possamos editar e compilar o firmware por nós mesmos?
> 
> # deslocamento de teste: 4096 0x1000
> caso ok
> # CONNECT BAUD: 115200
> ..... _****.....****_ ..... _****.....****_ ..... _****.....****_ ..... _****.....****_ ..... _****.....****_ [2021-10-14 06: 17: 58,473] [ESP8266Loader_spi [1]] [espDownloader.py] [linha: 351] [ERROR]: Erro de sincronização do chip: Falha ao conectar ao ESP32: Tempo limite excedido aguardando cabeçalho do pacote [2021 -10-14 06: 17: 58,474] [ESP8266Loader_spi [1]] [espDownloader.py] [linha: 439] [ERROR]: Erro de sincronização do chip ESP32 esp_sync_blocking.
> 
> ![imagem](https://user-images.githubusercontent.com/92496978/137302562-2b15de3a-b7c9-40dc-b175-4ad32d5aae15.png)

Defina BAUD: 115200 e @=0
![Sem título](https://user-images.githubusercontent.com/27018751/141879803-63543ad3-5022-4a47-b827-fa7ec651c349.png)

**Comment by makerbase-mks** [comment]
@grumpyduck300 , the latest firmware has enabled the Z axis: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/TS35/CNC/Normal. 

For upload problem, please refer to [#19](https://github.com/makerbase-mks/MKS-DLC32/issues/19#issuecomment-978785658)

**Comment by makerbase-mks** [comment]
Please try, I close this issue now. Please reopen it if you still have problem.
