### ISSUE TITLE
Spindle port into 0-10v

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#180]
Can you change or upgrade the spindle port into 0-10v? Since I need that port to control my spindle speed, thx u

**Comment by abinoer** [comment]
Does the motherboard's current condition not apply to your spindle

**Comment by kweilim98** [comment]
Yes , but nve mind , I think I will use the pwm to analog converter module

**Comment by abinoer** [comment]
#178
