### ISSUE TITLE
Cnc firmware update

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#182]
When the new firmware for CNC user will available? 2 months more ago I m waiting for it

**Comment by manuelchaves** [comment]
An update is unlikely right now, because China is goin through some problems. I too am loocking forward to updates. Tks

**Comment by kweilim98** [comment]
the lasted firmware for cnc already release by today, maybe will be update a bit later

**Comment by abinoer** [comment]
There are still some bugs to fix, we will update them as soon as possible
