### ISSUE TITLE
X,Y, Z probe

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#187]
Does the features will update with 3axis probe? 
![IMG-20220411-WA0030](https://user-images.githubusercontent.com/66898187/163791101-cb889727-e874-4bb4-8d7b-fc01c3f0d2a3.jpeg)

**Comment by abinoer** [comment]
Do you mean the z-axis tool probe here

**Comment by kweilim98** [comment]
No, I mean the X，y and z touch probe, to set the workpiece coordinate in origin and more precise

**Comment by kweilim98** [comment]
Now only have the z tool probe only

**Comment by daxliniere** [comment]
@kweilim98 Assuming your 3-axis probe has a sinlge output, it can all be done with a macro in UGS.

This is my Z-axis probe macro, but it could conceivably be modified for X and Y axes:

```
G21
G91 G38.2 Z-46 F100
G0 Z1
G38.2 Z-2 F50
G10 L20 P1 Z4.985
G10 L20 P2 Z4.985
G10 L20 P3 Z4.985
G10 L20 P4 Z4.985
G10 L20 P5 Z4.985
G10 L20 P6 Z4.985
G90 G0 Z20
G90
```
