### ISSUE TITLE
M4 is not working om Makersbasew MKS DLC 32 V2.1

### ISSUE THREAD

**Issue by Pero1959** [makerbase-mks/MKS-DLC32#189]
[](https://www.facebook.com/photo/?fbid=4709842565791698&set=gm.1084691495721172&__cft__[0]=AZX_iMuNhmr0oqKVyDkQIv34PckA2jSt_ndSzKwNslfNOo1wmRPRt7in7KVJWfHwjUzb-HXvG4AqgHQGNUHXXM9i1BKUylyjRjr3Rtig1iu1-IPLUypZ4IRJjt-okTOeYuJseZiZ0S6vdlRxdK3F-eK23IllVbGCymjHSU83UJVoHJx1X_mMqB_SxMbacdBAPpg&__tn__=EH-R)Hi there, some help please
Since iám using the makerbase mks dlc v2 0 shield i get these faults on my cnc 3018. 
my GRBL setting $32=1 so why do i get M4 fault

![image](https://user-images.githubusercontent.com/104031641/164083250-47f74c0f-d0b8-4562-a4fe-d533f6c3b7dd.png)

**Comment by abinoer** [comment]
![1650442259(1)](https://user-images.githubusercontent.com/96047125/164182354-74c1c099-d112-420b-bea5-a3c1f870b1eb.png)
https://lasergrbl.com/usage/raster-image-import/target-image-size-and-laser-options/#laser-modes
This is the official description of GRBL, M4 does not work when $32=0, and the CNC firmware is fixed $32=0, so it is useless to modify the configuration $32. Therefore, CNC cannot use M4
