### ISSUE TITLE
Not going into bootloader mode

### ISSUE THREAD

**Issue by grumpyduck300** [makerbase-mks/MKS-DLC32#19]
I have tried everything I can think of to get my board into bootloader mode and it wouldn't work. 
I can communicate with the board esptool.py runs but it stays in operational mode failing the sync. Any help will be appreciated. I can't use my laser tell I figure this out.

**Comment by solawc** [comment]
> I have tried everything I can think of to get my board into bootloader mode and it wouldn't work. I can communicate with the board esptool.py runs but it stays in operational mode failing the sync. Any help will be appreciated. I can't use my laser tell I figure this out.

The download mode of ESP32 is controlled by the starting level of GPIO. If you ensure that the CH340 driver on the serial port and PC is complete, please help check the level of IO0, Probe at power-on, or they Is there an external device?

**Comment by makerbase-mks** [comment]
@grumpyduck300 We found some computer's usb cannot support the valid signal to reset the board, even add the capacitor as @rlinta mentioned, some computers are still unavailable. If you cannot make it enter download mode, you can connect the two pins together(pull gpio0 to gnd), and power on the board to enter download mode. And disconnect the two pins and re-power the board to work normally.

![1637810267(1)](https://user-images.githubusercontent.com/12979070/143373793-188ccae4-2313-4882-b688-2fb59fec0a96.png)

**Comment by idilbaz** [comment]
> @grumpyduck300Bazı bilgisayarların usb'sinin kartı sıfırlamak için geçerli sinyali destekleyemediğini, hatta kapasitörü aşağıdaki gibi ekleyemediğini gördük.@rlintaBahsedilen, bazı bilgisayarlar hala kullanılamıyor. İndirme moduna giremezseniz, iki pimi birbirine bağlayabilir (gpio0'ı gnd'ye çekin) ve indirme moduna girmek için kartı açabilirsiniz. Ve iki pimin bağlantısını kesin ve kartın normal şekilde çalışması için yeniden güç verin.
> 
> ![1637810267(1)](https://user-images.githubusercontent.com/12979070/143373793-188ccae4-2313-4882-b688-2fb59fec0a96.png)

There is no such place on my card. Where exactly is it ?

![ssss](https://user-images.githubusercontent.com/102018170/188276158-469fb4d4-8fc3-4fb3-b3da-9cdcbbc7ad1e.jpg)

**Comment by Uraharadono** [comment]
Posting this as well in hopes it helps someone in future. I am using MKS TinyBee.

 Connect wires as so: 

<img width="1350" height="1800" alt="Image" src="https://github.com/user-attachments/assets/6cc6a161-1bc8-4077-8bd7-cbadb792890e" />

<img width="800" height="800" alt="Image" src="https://github.com/user-attachments/assets/b6be22f6-9f7b-43bf-9825-9a2e06e2b83b" />

 So left pins on rows 2 and 5.
Hold reset button while connecting - or if that doesnt work release it just before installing FluidNC and it should work.
