### ISSUE TITLE
Setting XY_Pos / Z_Pos doesn't work via touch

### ISSUE THREAD

**Issue by bbuster2** [makerbase-mks/MKS-DLC32#191]
I am having trouble to set the XY or Z position via the TS35 display.
In the Control and the Sculpture menu i can press the XY_Pos or Z_Pos button which should set the X, Y and Z position to zero.

It doesn't effect the positions at all so when i run my program, the X, Y and Z moves to a complete wrong position and destroys my workpiece.

Is this a bug or am i doing something wrong. I also have the z-probe but didn't use it yet.

I am using the CNC firmware

**Comment by abinoer** [comment]
XY_Pos/Z_Pos functions are normal. Can you provide a video that can't be set to have a look
