### ISSUE TITLE
problemi vari

### ISSUE THREAD

**Issue by massimop3632** [makerbase-mks/MKS-DLC32#193]
buona sera a tutti
ho da qualche tempo in uso la mks dlc32 senza tft e fino a settimana scorsa tutto andava bene 
adesso improvvisamente ho riscontrato i seguenti problemi:
i comandi m3, m5 e s non funzionano piu
il ciclo di home non funziona, la testa si muove di circa 10 mm e poi va in allarme
il ciclo di probing funziona solo se i contatti sono chiusi, in questo caso la testa si muove in z+
se separo i contatti va subito in allarme
allego i settaggi del mio grbl.
uso ugs platform come gcode sender
[settaggi.odt](https://github.com/makerbase-mks/MKS-DLC32/files/8577545/settaggi.odt)

**Comment by abinoer** [comment]
What do you use it for? Could you describe it in more detail? It is better to provide video or pictures. In addition, can YOU use English? I can't understand the questions you mentioned.
