### ISSUE TITLE
Yes, we can modify for you. You can send the image.

### ISSUE THREAD

**Issue by LuisCnMan** [makerbase-mks/MKS-DLC32#198]
Yes, we can modify for you. You can send the image.

_Originally posted by @makerbase-mks in https://github.com/makerbase-mks/MKS-DLC32/issues/127#issuecomment-1030569749_

**Comment by LuisCnMan** [comment]
> Yes, we can modify for you. You can send the image.
> 
> _Originally posted by @makerbase-mks in [#127 (comment)](https://github.com/makerbase-mks/MKS-DLC32/issues/127#issuecomment-1030569749)_

**Comment by LuisCnMan** [comment]
Que características debe tener

**Comment by LuisCnMan** [comment]
![219822948_342271320965498_5453185631617651241_n](https://user-images.githubusercontent.com/104740969/166170266-750b260d-ef8b-4d50-9eff-762bd78253ef.jpg)

me gustaría tener este logo en la pantalla principal

**Comment by LuisCnMan** [comment]
me gustaría tener este logo en la pantalla de inicio 

![Logo](https://user-images.githubusercontent.com/104740969/166170395-d905d66d-7ba0-40d8-8715-64a5ab395a80.jpg)

**Comment by UlisseDanilo** [comment]
hi, what is the process to correctly create a custom logo?
