### ISSUE TITLE
Enable Hard Homing

### ISSUE THREAD

**Issue by Klaus3777** [makerbase-mks/MKS-DLC32#199]
Hello,
with which parameter can you activate the hard homing?
It is disabled on the display.

Greetings Klaus

**Comment by abinoer** [comment]
![1651636174(1)](https://user-images.githubusercontent.com/96047125/166620842-280892e3-4d85-49ac-8b6d-af9e6e97a43f.jpg)
https://github.com/makerbase-mks/MKS-DLC32/wiki/Firmware
$21=1and$22=1

**Comment by Klaus3777** [comment]
Hello,
this can now be switched on at the display, but after homing the error message "Homig fail, pleas unlock" comes up.

**Comment by abinoer** [comment]
Do you have a machine to test? After clicking the button, is the return normal? Can the machine stop when it meets the limit

**Comment by Klaus3777** [comment]
this is my test machine, 
after the return and reaching the limit switches comes this message and it stops at X=1 and Y=1

**Comment by abinoer** [comment]
Which firmware are you using? Have you tried to slow down the return? You'd better provide a video

**Comment by Klaus3777** [comment]
![Achsen](https://user-images.githubusercontent.com/65283206/167373018-deeb8bc7-e390-4f13-b8d3-7718c004db8d.jpg)
Hello, 
Update to V2.0.8_H35_20220105_N,
Homing no longer works properly , axes are reversed in the running direction.
Where is the correct home point?
could you set it that way?
if so, how?

**Comment by abinoer** [comment]
https://github.com/makerbase-mks/MKS-DLC32/wiki/Firmware
Refer to the instructions and adjust the parameters to change direction. If soft limits and hard limits are on at the same time, zero must be in the lower left corner.

**Comment by abinoer** [comment]
https://github.com/makerbase-mks/MKS-DLC32/wiki/Firmware
Refer to the instructions and adjust the parameters to change direction. If soft limits and hard limits are on at the same time, zero must be in the lower left corner.
