### ISSUE TITLE
what is the A axes

### ISSUE THREAD

**Issue by killrob** [makerbase-mks/MKS-DLC32#20]
I've noticed, connecting Ligthburn to the board, that there is an "A" axes... for which use is this? and LaserGRBL do not recognise $103, $113, $123 and $133 as valid parameter as you can see from configuration machine on both programs
![LG](https://user-images.githubusercontent.com/9749941/137816686-c589d80a-964a-4b93-9fea-5c08ef576994.png)
![LB](https://user-images.githubusercontent.com/9749941/137816695-c60ecfe0-2839-481d-85d7-f1dc82ccb020.png)
.

**Comment by solawc** [comment]
> I've noticed, connecting Ligthburn to the board, that there is an "A" axes... for which use is this? and LaserGRBL do not recognise $103, $113, $123 and $133 as valid parameter as you can see from configuration machine on both programs ![LG](https://user-images.githubusercontent.com/9749941/137816686-c589d80a-964a-4b93-9fea-5c08ef576994.png) ![LB](https://user-images.githubusercontent.com/9749941/137816695-c60ecfe0-2839-481d-85d7-f1dc82ccb020.png) .

Wie Sie sehen, sind einige Konfigurationsfunktionen vorhanden, aber nicht geöffnet, dann muss die Konfigurationsdatei beim Update auf Menge geprüft werden, damit sie zusätzlich hinzugefügt und bei nachfolgenden Updates entfernt wird, und das Z Achse wird zur Verfügung gestellt

**Comment by solawc** [comment]
> I've noticed, connecting Ligthburn to the board, that there is an "A" axes... for which use is this? and LaserGRBL do not recognise $103, $113, $123 and $133 as valid parameter as you can see from configuration machine on both programs ![LG](https://user-images.githubusercontent.com/9749941/137816686-c589d80a-964a-4b93-9fea-5c08ef576994.png) ![LB](https://user-images.githubusercontent.com/9749941/137816695-c60ecfe0-2839-481d-85d7-f1dc82ccb020.png) .

As you can see, some configuration functions are available, but not open. Then the configuration file needs to be checked for quantity when it is updated, so it will be added in addition, and it will be removed in subsequent updates, and the Z axis will be provided. control

**Comment by solawc** [comment]
> sorry @solawc but i've not understood what you mean

As you can see, the new grbl is reserved for multi-axis control, except for the common X, Y, and Z axes. If a new axis is required, it is the A axis, but on the current motherboard, Not used, so you can ignore this configuration item
