### ISSUE TITLE
MKS-DLC32 WIFI Access Point

### ISSUE THREAD

**Issue by BigJuicee** [makerbase-mks/MKS-DLC32#200]
What is the configuration for the Wi-Fi access point?
This is what I have right now, but I don't know what's wrong or what else I need.

//--WIFI configuration---//
$ESP115=ON
$ESP110=AP
$ESP131=8080	
//wifi name
$ESP105=MAKERBASE3D 	
//wifi password，：[ESP106]makerbase3d
$ESP106=makerbase3d	
$ESP107=192.168.0.1
$ESP108=1
$ESP120=ON
$ESP121=80

**Comment by abinoer** [comment]
![1651808091(1)](https://user-images.githubusercontent.com/96047125/167063287-643b55ae-8b5e-4d2e-a7ea-3ff3b598a7e6.jpg)
You just need to change the wifi name and wifi Password in this file. However, you can use MKSLaserTool to connect to WiFi, which is much easier and faster

**Comment by BigJuicee** [comment]
How would I use the MKSLaser Tool to connect to WiFi? I want to have it set up so it gives me an IP address but I can't figure it out.

**Comment by abinoer** [comment]
![1651817168(1)](https://user-images.githubusercontent.com/96047125/167076188-8006a446-b906-45d2-baca-bef948695f66.jpg)
This software, after you download and install, select the correct COM port to connect, enter the name and password to connect to WiFi, there is a button to obtain IP, very simple, you try

**Comment by BigJuicee** [comment]
Could you give me an example of what the code would look like?

**Comment by abinoer** [comment]
![1651892635(1)](https://user-images.githubusercontent.com/96047125/167235603-74e4ca45-200b-4369-bec3-f5732d62acfc.jpg)
![1651892707(1)](https://user-images.githubusercontent.com/96047125/167235604-53907f22-4131-4840-9551-217ac93bc5de.jpg)

**Comment by BigJuicee** [comment]
Is that in the configuration? Could you send the txt file? I need something to work off of that would get me in the right direction at least. The Wi-Fi settings in the dlc_cfg.txt wouldn't work for me.

**Comment by abinoer** [comment]
![1651904758(1)](https://user-images.githubusercontent.com/96047125/167241810-262b9ea7-39bc-4661-8dbf-6ab48b468987.jpg)
![image](https://user-images.githubusercontent.com/96047125/167241830-59d04a28-4279-446b-9cc2-a70f20e5404d.png)
1. Copy the modified configuration file to the TF card, insert it into the motherboard, wait for about two minutes, and then connect to WiFi after restart
2. Connect using MKSLaserTool
3. Connect by command
All of the above methods can be connected to WiFi, You can connect in another way,the most convenient is through MKSLaserTool

**Comment by 3DSmitty** [comment]
@abinoer this makes no sense. Anyone familiar with programming ESP32 knows "STA" mode  means it is a client station on a wifi network. I believe the original question is how to set this up as a wifi access point as FluidNC does by default. Does the DLC32 support "[ESP110] AP" setting and if so what would the whole configuration look like?

**Comment by sfcroccaforte** [comment]
$ESP110=AP or $ESP110=STA
