### ISSUE TITLE
output power  J6/J13

### ISSUE THREAD

**Issue by Bavarianarms** [makerbase-mks/MKS-DLC32#207]
Hi guys, i like to supply 2 JMC integrated steppers with J6 and J13. Do you know how many A at 24V they can provide?
Thank you verry much!

**Comment by abinoer** [comment]
Do you want to know the maximum output power supported by the motherboard? This document may also help you.https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf
