### ISSUE TITLE
$1 = 255 after boot motors don't move

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#21]
As the topic says: When I set $1 to 255 (stepper-motors should keep enabled with no delay), the motors do not work at all. Only when setting it to 0...254 and rebooting the machine, the stepper-motors will work again.

**Comment by trashypopashy** [comment]
@mks-viva @makerbase-mks @solawc any idea, how to solve this?

**Comment by trashypopashy** [comment]
once again: @mks-viva @makerbase-mks @solawc any idea, how to solve this?

**Comment by solawc** [comment]
> As the topic says: When I set $1 to 255 (stepper-motors should keep enabled with no delay), the motors do not work at all. Only when setting it to 0...254 and rebooting the machine, the stepper-motors will work again.

This problem has been solved enough. I am finishing the firmware of V1.1 version. After finishing finishing, it will upload. This will solve the problem of the motor not moving due to $255=1.

**Comment by makerbase-mks** [comment]
Have you tried the latest firmware: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/TS35/Laser ? It has been fixed.
