### ISSUE TITLE
End Stop/Limit switch Signal pin voltage tolerance? 

### ISSUE THREAD

**Issue by MTRatcliffe** [makerbase-mks/MKS-DLC32#210]
Hi, After reading the wiring document and browsing the schematic files [page 6/9], lm struggling to verify if the limit switch inputs are 5v tolerant or not? 

Could anyone confirm the voltage range for the end stop inputs?

**Comment by manuelchaves** [comment]
5V

**Comment by abinoer** [comment]
Yes, 5 v
