### ISSUE TITLE
DLC32 TS35 firmware and Bluetooth

### ISSUE THREAD

**Issue by PA3CCE** [makerbase-mks/MKS-DLC32#211]
Hi,

I recently bougt the DLC32-TS35 hardware so I am new to this group.
I`m  intending to use is for my CNC machine, so I downloaded and installed tthe latest Nomal CNC  V2.1 l (20220510)  version of firmwre and like the new CNC usernterface........ I presume I can use the CNC PC softwares (like Candle) as well ??

Nice to see the WiFi being supported in the firmware and I would appreciate VERY much when Bluetooth wouldl be implemented as well !!

Thank you and best regards,
Jos (PA3CCE)

**Comment by abinoer** [comment]
Yes, you can, all support GRBL protocol host computer can
