### ISSUE TITLE
LOGO CUSTOM

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#213]
when the logo can be custom and open source? Just like the tft can use the mks tool to custom the icon. When dlc will be?

**Comment by aviador58** [comment]
Has it been possible to solve this issue? I want to personalize my plate.

**Comment by kweilim98** [comment]
> Has it been possible to solve this issue? I want to personalize my plate.

Not sure, I m still waiting too

**Comment by Medina-ui** [comment]
Hi, No updates I can see at the moment! Still waiting too. Almost 2 Months since it has been move to "In progress" and I have several boards, tft's and machine enclosures waiting for this. Thinking about returning to old one.....

**Comment by aviador58** [comment]
gracias por contestar.

**Comment by aviador58** [comment]
I don't understand how they don't open the code more to be able to get more out of these boards, we are going to have to go back to the usual open source boards, because they are updated much more to the new needs of the users.

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE

**Comment by sharknetwork24** [comment]
The solution to change the image to your display.

https://github.com/makerbase-mks/MKS-DLC32/issues/390

**Comment by burak1000** [comment]
i tried many times this method but i cant do it. it's simply not works

**Comment by Medina-ui** [comment]
I burak1000. Send me the image and tell me what version of firmware you need. I can do it for you
