### ISSUE TITLE
How to connect included Z-Probe for CNC

### ISSUE THREAD

**Issue by bbuster2** [makerbase-mks/MKS-DLC32#217]
I want to test the included Z-Probe. It comes with 2 wires.
On the PCB there is a Probe connector but it has 3 connections. 5V, GND and S (signal).

How do i have to connect the Z-Probe?
The probe comes with a 2 pin connector so i assume i have to connect it to GND and Signal, but when i use the knife button on the latest firmware, it says "setting probe" but when i hold the probe to the holder nothing happens.

How does the Z-Probe work? 
Also, the display keeps showing:

```
INFO

Setting probe...
```

I cannot cancel it or it doesn't stop after a minute or so

**Comment by abinoer** [comment]
Do you have an installation test? Can you upload the video

**Comment by bbuster2** [comment]
What do you mean with an installation test?
And where do you want me to upload the video? I think i added it in the previous email?

Verstuurd vanaf mijn iPhone

Op 1 jun. 2022 om 04:03 heeft abinoer ***@***.***> het volgende geschreven:

﻿

Do you have an installation test? Can you upload the video

**Comment by abinoer** [comment]
Connect the ground and signal pins of the interface to the tool

**Comment by bbuster2** [comment]
Thank you. And how can i test / use it?

**Comment by abinoer** [comment]
The signal line is connected to the cutter head, and the contact of the ground wire connection is quickly put under the cutter head, and it can be used

**Comment by Murik** [comment]
How can i set probe thickness to use in offline or web software?
