### ISSUE TITLE
X Y Z Probe

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#219]
When the X y and z probe features will be added for CNC firmware? The rite now only have z probe only. The CNC user mostly need the X y z probe to setting the workpiece into home or origin position for more precise work. This probe features just like what have in ugs platform

**Comment by kweilim98** [comment]
@solawc I have been told that the alarm 4 probe fail is because not add in the X y z probe function in the board that cause the  probe fail

**Comment by abinoer** [comment]
Sorry, we have decided not to develop the function you mentioned, the firmware has been open source, you can modify it yourself
