### ISSUE TITLE
Spindle TTL output only 4.89V DC

### ISSUE THREAD

**Issue by daxliniere** [makerbase-mks/MKS-DLC32#221]
Hello,
It seems that the spindle TTL output pins (J18) only put out a maximum of 4.89V DC. Is this a known issue and is there a hardware workaround I can apply?

All the best,
Dax.

**Comment by abinoer** [comment]
4.89 V? You measure it with a voltmeter? You should use an oscilloscope to look at the duty cycle. The maximum duty cycle is 100%
