### ISSUE TITLE
MKS-DLC 32 firmware V2.0.8_H35_20220105_N.bin problem

### ISSUE THREAD

**Issue by msmahm48** [makerbase-mks/MKS-DLC32#222]
Hi
I have updated my MKS-DLC 32 V2.1 firmware to the V2.0.8_H35_20220105_N.bin. The homing works OK for all the three-axis. But the laser is not working. I checked the $32 and it's 1. Any suggestion on how to solve this problem?
Thank you.

**Comment by abinoer** [comment]
Laser not working? Is the wiring wrong? What is the motherboard model you are using, is the firmware in board_v1.0 or board_v2.0?

**Comment by msmahm48** [comment]
The motherboard is  MKS-DLC 32 V2.1 and I am using the firmware in  board_v2.0. The laser wiring is correct because I have checked it with other firmware on the same board.

**Comment by abinoer** [comment]
![1654135745(1)](https://user-images.githubusercontent.com/96047125/171533203-959149ae-3f96-4649-9e86-3f26bb735776.jpg)
How do you turn on the laser? Will the indicator light turn on after sending the command "M3 S1000 G1 F1000"?

**Comment by msmahm48** [comment]
I am using Lightburn. The indicator is off always even after sending the command "M3 S1000 G1 F1000".
This is my setting:
$25=1000.000
$26=250.000
$27=1.000
$28=1000.000
$30=1000.000
$31=0.000
$32=1
$38=1
$40=1
$100=80.000
$101=80.000
$102=520.000

**Comment by abinoer** [comment]
You re burn the firmware, if the indicator light still does not light after sending instructions, there should be a problem with the motherboard, then you contact customer service

**Comment by msmahm48** [comment]
Hello
You are right. I don't know how that has happened. The firmware file V2.0.8_H35_20220105_N.bin that I have was something wrong with it. I downloaded a new copy and it is working as expected. 
Thank you so much.
