### ISSUE TITLE
Flash Download Tool 3.9.2 CombineBin

### ISSUE THREAD

**Issue by gbconnet** [makerbase-mks/MKS-DLC32#228]
With this software version (selecting chipType "ESP32" and workMode "develop") the "CombineBin" button creates a target.bin file that does not work (with version 3.8.5 and earlier it does. SpiFlashConfig SPI SPEED "80MHZ", SPI MODE "DIO")

**Comment by abinoer** [comment]
![1654740714(1)](https://user-images.githubusercontent.com/96047125/172749482-3d410038-1f92-4eea-a5fc-d825b82b1d59.jpg)
@gbconnet Try using this dedicated download tool

**Comment by solawc** [comment]
Please select dout mode to merge, it will be more compatible. Make sure that the address assigned on your compiled CSV is correct
