### ISSUE TITLE
Stepper Motors Stall If The Speed Is Over 1500

### ISSUE THREAD

**Issue by BigJuicee** [makerbase-mks/MKS-DLC32#229]
I have 2 NEMA 34 stepper motors and they stall if the speed is over 1500 mm/sec. I have the pulse and resolution to where they move the correct distance that I tell it to but I can’t get it to move as fast as a laser should. My stepper drivers are DQ860MA and they are set to 1600 pulse/rev and my X and Y axes travel resolution is 320. I don’t know what I have to adjust so the motors don’t stall and that they move the correct distance.

**Comment by abinoer** [comment]
Will stop? What do you mean? Can't move faster than 1500? Could you possibly provide video to see what's going on

**Comment by solawc** [comment]
Please ensure that:

1. Your power supply is stable

2. Do you have a 4988 driver in your hand? Have you tested the 4988?

**Comment by BigJuicee** [comment]
![DFE289CC-A2FD-4BFA-BBE0-1750CE0A4918](https://user-images.githubusercontent.com/105027332/173854318-ecd0873c-d8c9-4296-84e5-3da6eaa9c607.jpeg)

https://user-images.githubusercontent.com/105027332/173854320-0706b7b6-7209-49c1-b766-69e57687cb6c.MOV

![04CF8155-020D-468D-AF73-CE3F8D281B3D](https://user-images.githubusercontent.com/105027332/173854323-cff54442-02fb-4d13-a5ef-5a40fc29ec7a.jpeg)
![4A71C32B-FAB5-4AE4-9E6C-F2200D730C43](https://user-images.githubusercontent.com/105027332/173854325-5fa7df13-1577-4046-b53c-b082cca0c507.jpeg)
![94CC1284-C4B4-4CE9-ADE2-E7AD6A1E52E8](https://user-images.githubusercontent.com/105027332/173854328-1f7cf1ac-0b08-48bf-a4df-840a15867f19.jpeg)
![8412C787-611A-4CAC-B77D-742E7B465E79](https://user-images.githubusercontent.com/105027332/173854331-bf5715a4-d4e5-498e-bd52-260a9e64ff59.jpeg)
![A22A259F-3EF6-46F9-BD70-A8D28653DE23](https://user-images.githubusercontent.com/105027332/173854335-db63cbc2-835a-414e-8e55-f06ced42e421.jpeg)
![DD0A0839-EAE0-4ED9-95DC-00A1B4B3FACB](https://user-images.githubusercontent.com/105027332/173854337-fb83e4b6-8395-4cff-9ac5-38ca6b77b58c.jpeg)
![FB0C2144-5054-4035-8848-0575DAA99F7D](https://user-images.githubusercontent.com/105027332/173854342-7b4ef1b0-dc1c-4e5d-9fd2-e452f28e8361.jpeg)
![9E5C963D-3642-4C72-9314-7E2E005E522F](https://user-images.githubusercontent.com/105027332/173854344-d8f3db80-e0a7-4b0e-937e-fcf26f4aed3f.jpeg)

**Comment by BigJuicee** [comment]
The 4988 driver is being used for the z-axis and the NEMA 34’s are being used with the drivers in the photos above.

**Comment by BigJuicee** [comment]
When I change the pulse/rev it doesn’t move the correct distance in mm that I tell it to.

**Comment by abinoer** [comment]
You can adjust the value of $100, $101, and $102 to get it right

**Comment by BigJuicee** [comment]
Wouldn’t that be going up if the motor is set to 1600 for the pulse/rev?

**Comment by abinoer** [comment]
If the distance is not correct, just adjust $100, $101, and $102

**Comment by BigJuicee** [comment]
What should I have the current to the motors set to?

**Comment by abinoer** [comment]
This needs to be set according to the load and motor parameters, so I can't give you any suggestions
