### ISSUE TITLE
Add pads for RXD0 and TXD0 in future

### ISSUE THREAD

**Issue by tuxcnc** [makerbase-mks/MKS-DLC32#230]
These are only two pads on PCB, but it will allow you to connect, for example, the HC05 or similar module.
ESP32 have Bluetooth, but it is not available if you using wi-fi.
HC05 module is cheap and transparent for data, no code is needs.

**Comment by solawc** [comment]
Hc05/hc06 are both good Bluetooth modules. They can be connected directly by using rx-tx-vcc-gnd, and have been paired with at commands. Our PCB has not made a compatible design for them. If you want to use them, of course, they can only be connected by flying wires

**Comment by tuxcnc** [comment]
>  Our PCB has not made a compatible design for them.
I wrote because I know.
Next version of PCB may be compatible, and it is zero cost in production, only a small change of project.
