### ISSUE TITLE
pwm signal convert to analog not simultaneously for spindle speed

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#233]
Hi, I am using a 600w 310vdc brushless spindle which uses the analog to variable the spindle speed by using the converter module from the TTL port. But the problem is the spindle speed was not simultaneously according to the speed have been set in the software. For example, I set m3 s700, and the actual speed rotation for the spindle was in 10k rpm something and also be the max speed for my spindle, so how to solve it?
![WhatsApp Image 2022-06-15 at 3 44 51 PM](https://user-images.githubusercontent.com/66898187/173771869-79acf62f-0555-43d4-804e-994f50446eb6.jpeg)
![WhatsApp Image 2022-06-15 at 3 44 51 PM (1)](https://user-images.githubusercontent.com/66898187/173771880-7c220996-e9e0-4fcf-8224-803b8b513ac1.jpeg)

https://user-images.githubusercontent.com/66898187/173771986-997b9c12-586f-4303-bd2b-de4552fe7c0f.mp4

https://user-images.githubusercontent.com/66898187/173772017-03ccb787-7040-4969-a54a-fa75dc913689.mp4

**Comment by abinoer** [comment]
For the convenience of management, unity is discussed here #216
