### ISSUE TITLE
MKS GIT...we can help you

### ISSUE THREAD

**Issue by giordy72** [makerbase-mks/MKS-DLC32#235]
Dear MKS,
we all had seen you have some serious problems with GIT.
It's more than a year we are waiting for the code!
You better read the manuals if you are not able to release the sources of the firmware.
Otherwise you can post a request here so we can help you to release the code.
Last but not least...send it by email so a volunteer can put it online.
I want to remind, you are using open source codes...don't follow the bad example of BTT with their LPC boards...
Respect the licensing terms, 'cause you are using sw in a commercial product.
I've throw away 15€ with your board, cause in the actual state it's crappy.
Think about it

**Comment by serial-tintypist** [comment]
...and now watch them never respond🤮

**Comment by Plottmania** [comment]
there you can wait, wait, wait and wait....

**Comment by Medina-ui** [comment]
Dear MKS,

Any news about it? I have several of these boards and I would like to use it. But at this point with no sourcecode released its impossible! Please realease sourcecode like you have done in other boards

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
