### ISSUE TITLE
Servo motor DLC32

### ISSUE THREAD

**Issue by Swarlo1** [makerbase-mks/MKS-DLC32#236]
Hello how can i use a servo motor 50Hz on the DLC32? Is this even possible? 
Thank you.

**Comment by abinoer** [comment]
https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf
You can use external drive to connect, the motherboard has external drive interface

**Comment by istinnstudio** [comment]
Is there a how to for this? how to connect and how to setup/config? (in order to use z-axis connection port/driver as a pen up/down mechanism for a coreXY plotter)

**Comment by andeecollard** [comment]
@istinnstudio I would also like to know this!

**Comment by Junior37534** [comment]
i also need this

**Comment by istinnstudio** [comment]
some info here but not an exact how-to: https://forum.v1e.com/t/configure-mks-dlc32-for-pen-plotter-hbot/38434
