### ISSUE TITLE
MKS DLC32 Normal Laser mode with Z axis

### ISSUE THREAD

**Issue by s1475478** [makerbase-mks/MKS-DLC32#238]
Dear All

just to check with you guys, is the Z axis works in Normal Laser mode yet?
I had been digging around but with no luck,

was thinking to flash the latest firmware which is : V2.0.8_H35_20220105_N.bin, however, found that mine board are loaded whit :V2.08(8M.H35.20220114)

any suggestion?

**Comment by abinoer** [comment]
Z-axis control buttons have been added
