### ISSUE TITLE
Z axis movement on laser

### ISSUE THREAD

**Issue by Lazarus-Rising** [makerbase-mks/MKS-DLC32#24]
Just to clarify, will this board in it's Normal Laser form allow the Z axis to be moved such as in Lightburn?

**Comment by mks-viva** [comment]
Generally speaking, the laser mode. Only X Y axis movement.

**Comment by Lazarus-Rising** [comment]
what about those lasers with motorised z carriages? this is an essential part of some of our designs we want to use these boards on.
would it be better to use the cnc version and set $31=1 in grbl?
