### ISSUE TITLE
V2.10_H35_2022_0621_N_ZX_001 BUG

### ISSUE THREAD

**Issue by Insigma1** [makerbase-mks/MKS-DLC32#247]
Hi there appears to be a bug with the latest version firmware V2.10_H35_2022_0621_N_ZX_001 , after Flashing the DLC32 V2.1 I found that using manual control from the LCD X axis is reversed, however using the Web interface with the same Firmware X moves in the correct direction

All other Axis move as expected it seems to only be X effected and only from the LCD (tft35)

This issue is not present in previous version V2.0.8_H35_20220105_N

**Comment by antude1** [comment]
Yes, I have the same problem, I need a solution.

**Comment by Lasermax3000** [comment]
Improving the GUI -> check ;)

**Comment by josefosantos** [comment]
Same problem here

**Comment by abinoer** [comment]
It has been resolved, please update the firmware
