### ISSUE TITLE
Pinmap

### ISSUE THREAD

**Issue by RVAMike** [makerbase-mks/MKS-DLC32#248]
I wouldn’t really call this an issue I’m looking for the pinmap Showing what pins Numbers and Functions are on the  DLC32 V2.1 trying to get it configured with FluidNC thanks for your help

**Comment by manitoulin-maker** [comment]
wont ever be released

**Comment by abinoer** [comment]
![1658213170626](https://user-images.githubusercontent.com/96047125/179684182-d752c2fa-44cc-4ed9-8256-a05cf0b5f061.jpg)
https://github.com/makerbase-mks/MKS-DLC32/tree/main/hardware/MKS%20DLC32%20V2.1_003

**Comment by thiagolocatelli** [comment]
Those PDF's are not very helpful to those who can't read schematics and the PIN.pdf is incomplete. Can you add a Pin Map table to the README.md file the same way it was done for the  TinyBee? Example: https://github.com/makerbase-mks/MKS-TinyBee#pinmap

**Comment by abinoer** [comment]
The IO on TinyBee's PinMap is also extended by the extension chip, which is not available without the schematic

**Comment by errolt** [comment]
And the pin numbers in the PIN MAP pdf is wrong. 
SD DO: IO2 is actually IO12
EXP2 IO39 is actually IO19
