### ISSUE TITLE
Usar Cnc 3018 pro

### ISSUE THREAD

**Issue by antude1** [makerbase-mks/MKS-DLC32#249]
Good, I want to use your board on a cnc 3018 pro, and I have the option to use both a spindle and a laser.
But I find that your board does not support having the cnc option and the laser option at the same time.
My laser works through the TTl output and the spindle through its connector. 
Every time I want to change the tool I have to load a new firmware?
it's ridiculous

**Comment by abinoer** [comment]
Sorry, we can only update the firmware switch at present
