### ISSUE TITLE
connect to lightburn

### ISSUE THREAD

**Issue by antude1** [makerbase-mks/MKS-DLC32#250]
it is impossible for me to connect via usb to the mks dlc 32 board and TS35-R V2.0 screen to lightburn.
I can tell me how to do it, every time I connect the screen goes blank and lightburn is connecting and there is no way to access the machine.

**Comment by josefosantos** [comment]
Same problem here

**Comment by josefosantos** [comment]
I will try the V2.10_H35_2022_0621_N_ZX_001 update to see if it fixes.
