### ISSUE TITLE
Question About the laser outputs and the spindle

### ISSUE THREAD

**Issue by antude1** [makerbase-mks/MKS-DLC32#252]
Can you explain to me if the laser ttl outputs and the spindle outputs are outputs that cancel each other according to the board configuration?
let me explain, 
when you configure the board to use it in laser mode, I can put my 5.5w laser and make engravings and cuts with the laser (the laser is connected to the ttl output of the board), but I can't activate the spindle that is connected to the 2 pins terminal board with screws.
if i configure the board to use it in cnc mode i can use the spindle (connected to the 2 pins with screws), but i can't use the ttl output (3 pins) to use the laser.
is this correct?
well if it is correct, you should fix that issue, because those like me who have a 3018Pro with the spindle accessory and the laser accessory, it sucks to be every time you change the tool formatting the board and writing the appropriate firmware for each process.
Cheaper and simpler boards give you the option to do that process change without having to mash the firmware every time.

**Comment by abinoer** [comment]
I am very sorry that the spindle and laser cannot be used at the same time, because the same IO control is used.

**Comment by abinoer** [comment]
I am very sorry that the spindle and laser cannot be used at the same time, because the same IO control is used.
