### ISSUE TITLE
Web Interface Fails

### ISSUE THREAD

**Issue by baylockzathras** [makerbase-mks/MKS-DLC32#256]
Hi All, Running:
V2.10_H35_2022_0621_N_ZX_001

Seems when the Device accesses the SD Card, the web interface stops working.

Steps to re-produce:
Turn on with SD Card inserted.
or
Use LCD to show boundary of Burn.

Currently working around by:
Power cycling with SD Removed, then inserting SD Card after.

Has any one else found this issue?
Have a better solution?

Thanks.

**Comment by abinoer** [comment]
Sorry, limited energy, not timely reply.

We have not received similar feedback, maybe you can burn the latest firmware to see if the problem you mentioned still exists. If there is still this problem, we hope you can upload the video to see, so that we can find out the reason, thank you

**Comment by baylockzathras** [comment]
Apologies, I forgot about this post. Seems to be a compatibility issue with chrome. Works fine in edge.
