### ISSUE TITLE
I the source code available for this?

### ISSUE THREAD

**Issue by growlybearproductions** [makerbase-mks/MKS-DLC32#258]
I looked around but could not find it if it is.

**Comment by Medina-ui** [comment]
There are several requests for it, and MKS apparently is not willing to open 
I would very happy if they release it

**Comment by troth530** [comment]
MKS is in violation of GPL.  People who purchase their hardware should consider that overall they are harming the community.  This design is a very poor design, very slow in processing gCode anyway.

**Comment by ubergeekseven** [comment]
They basically stole the esp32 grbl project and modified it. They need to publish their source. The esp32 grbl people are fine with it as long as they state it.

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE

**Comment by troth530** [comment]
@makerbase-mks thank you.  I am interested in integrating your touch screen.
