### ISSUE TITLE
Info on v2.0 board 

### ISSUE THREAD

**Issue by AussieMakerGeek** [makerbase-mks/MKS-DLC32#26]
Where is support files for v2 of board now shipping? schematic, firmware etc. please upload.

I want to be able to disable Z homing but it requires firmware to be rebuilt.

**Comment by trashypopashy** [comment]
> Where is support files for v2 of board now shipping? schematic, firmware etc. please upload.

Where did You see a DLC32 V2?

@solawc @makerbase-mks @mks-viva are all the boards shipped in Version 2, now? Please show the differences!

**Comment by AussieMakerGeek** [comment]
I purchased via the official makerbase Ali store but received one like this
https://www.aliexpress.com/item/1005003511460756.html

**Comment by mks-viva** [comment]
@AussieMakerGeek I will upload it

**Comment by trashypopashy** [comment]
Do I still have a TTL-Output-possibility on the V2-Boards?

**Comment by mks-viva** [comment]
@trashypopashy 
Only 1 TTL has been reserved so far.

@AussieMakerGeek 
I has upload hardware sch and so on

**Comment by trashypopashy** [comment]
> @trashypopashy Only 1 TTL has been reserved so far.

@mks-viva You mean there is only the CNC-Spindle-PWM-Output with its 12/24V?

**Comment by mks-viva** [comment]
> > @trashypopashy Only 1 TTL has been reserved so far.
> 
> @mks-viva You mean there is only the CNC-Spindle-PWM-Output with its 12/24V?

Yes

**Comment by AussieMakerGeek** [comment]
yes, but in the same as the 8bit version there is a ttl output before the fet so it does do 3v ttl, its just on the logic side of the spindle fet.

**Comment by trashypopashy** [comment]
But there is no plugable interface anymore. I would need to solder, right?

**Comment by AussieMakerGeek** [comment]
no, there is now a 3 pin ttl,gnd,vin connector plus separate vin,gnd connector. I am already using it for my diode laser.

**Comment by mks-viva** [comment]
@AussieMakerGeek 
TTL is 5V output on dlc32 board
![image](https://user-images.githubusercontent.com/16629551/141254561-9beff8f3-cf33-4f91-b388-e8c52febef84.png)

**Comment by AussieMakerGeek** [comment]
@mks-viva thanks for all the info, can you briefly explain differences between 2.0 and 2.1?

**Comment by mks-viva** [comment]
Refer to here: https://github.com/makerbase-mks/MKS-DLC32/tree/main/hardware
![image](https://user-images.githubusercontent.com/16629551/141255557-7e425a41-9b8d-4318-933f-e1aae4fa9945.png)

**Comment by AussieMakerGeek** [comment]
sorry! I missed that bit. Thanks for clarification.
