### ISSUE TITLE
Z-Probe direction invert?

### ISSUE THREAD

**Issue by jer0177** [makerbase-mks/MKS-DLC32#261]
My machine (MKS-DLC32 v2.1 003, firmware v2.1.0) probes the Z-axis towards positive, not negative. 
I have limit switches on all axes, and it homes and travels properly, but it won't probe correctly. I've tried everything I can think of - can someone help?

**Comment by abinoer** [comment]
![1658746218049](https://user-images.githubusercontent.com/96047125/180760993-ec9fe1cf-8578-41f7-9c40-54004a1c89d0.jpg)
What instruction are you using? I use Candle. I use this command

**Comment by jer0177** [comment]
AH! I had tried everything I could think of *except* defining negative probe distance. 

That solved the problem! Thanks for your screenshot!
