### ISSUE TITLE
firmwar

### ISSUE THREAD

**Issue by benoit251** [makerbase-mks/MKS-DLC32#263]
bonjour,

je suis au bresil, et je n'arrive pas a telecharger les firmwar, tous les liens semble cassé, comment je peus faire ???

merci

**Comment by manuelchaves** [comment]
Olaá. Baixe por este link do [Github](https://github.com/makerbase-mks/MKS-DLC32/archive/refs/heads/main.zip)

**Comment by manuelchaves** [comment]
Ou se preferir, copie e cole
https://github.com/makerbase-mks/MKS-DLC32/archive/refs/heads/main.zip

**Comment by benoit251** [comment]
> Ou se preferir, copie e cole https://github.com/makerbase-mks/MKS-DLC32/archive/refs/heads/main.zip

Bom dia  Manuel, muito obrigado pelo link, isso resolvi meu problemo, agoro todo ta funcionando direitinio
