### ISSUE TITLE
Dual Y Limit Switch - Remapping Pins

### ISSUE THREAD

**Issue by ValeryOD** [makerbase-mks/MKS-DLC32#267]
DLC32 ships with laser normal firmware preinstalled. Autosquaring is a must for repeatability and precision of any cnc job, especially for laser works. Unless the laser is mounted on a more serious CNC machine, the Z axis is not a very common option for a dedicated laser build. Thereat on DLC32 the Z and Probe pins mostly stay unused which is much regret.
Please add an option to modify the pinout to make autosquaring possible, or since there is no uncompiled version of the firmware to be edited, please make available to download the firmware with the Probe/Z Limit pin remapped for the second Y. Thank you.

**Comment by abinoer** [comment]
Sorry, we don't have the energy to modify for each DIY customer, the firmware has been open source, please modify by yourself
https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
