### ISSUE TITLE
Disable Z axis homing

### ISSUE THREAD

**Issue by ErnieV** [makerbase-mks/MKS-DLC32#272]
Hi,
Most standard laser machines have no z axis. Homing is now impossible because firmware expects z axis switch. 
Can you please offer a firmware with z axis homing disabled? 

Thank you very much!

**Comment by a76664289** [comment]
上位机控制台发送
$Homing/Cycle0=XY 第一个循环XY同时归位。

或发送
$Homing/Cycle0=X 在第一个循环中归位 X，
$Homing/Cycle1=Y 第二个循环中归位Y。
