### ISSUE TITLE
Is it possible to change the Framing speed?

### ISSUE THREAD

**Issue by linx1clarke** [makerbase-mks/MKS-DLC32#273]
Hi,  

I have my board set up and working(after 4 hours of troubleshooting), and I am happy with it for the most part, but is there a way to increase the speed at which the engraver frames the project(before you start it so you can position the piece of material)?

I find the preset speed very slow, and for bigger projects, when you need to frame it multiple times, it is taking a very long time!

Can anyone help with this issue-Can someone tell me how to speed up frame speed?

Thanks!

**Comment by a76664289** [comment]
根据机型性能修改一下参数
最大速度设置
$100=5000
$111=5000
$112=5000

加速度设置
$120=1000
$121=1000
$122=1000
###

**Comment by linx1clarke** [comment]
I see these are for the speed settings, but my speed settings are at 6000mm/min and it is not doing that.  However, my acceleration is at 500, but I'm not sure that solves the issue, because I am not talking about the engraving process, just the speed of the frame process to position the piece of wood.

**Comment by abinoer** [comment]
Sorry, this speed does not support the user's own modification

**Comment by serial-tintypist** [comment]
> Sorry, this speed does not support the user's own modification

Let me correct you - sorry, this whole firmware does not support user's own modification (because we have stolen an open source project and could not care less).

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
