### ISSUE TITLE
MKS DLC32 V2.1, flash read err, 1000, after new firmware

### ISSUE THREAD

**Issue by Dettinger-15** [makerbase-mks/MKS-DLC32#275]
Hello, I bought a MKS DLC32 V 2.1.
Then I have flasht a new firmware on this board
(V2.0.8_H35_20211222_n.bin).
Since then, the error has been under LaserGrbl leafls: "flash read err, 1000" and the connection is interrupted after a while.
I installed the firmware with the MKS laser tool and with the flash download tool version 3.6.6 from Espressif. Both lead to the same mistake.
Can someone help me with my problem?

**Comment by abinoer** [comment]
Could you please provide a screenshot

**Comment by Dettinger-15** [comment]
I bought this board
![MKS-DLC32](https://user-images.githubusercontent.com/73053777/187196142-2ded4c5a-30d9-40f9-beae-b485fefd5ea2.jpg)
These are the error messages in LaserGRBL and about Serieller Monitor
![Arduino- erieller Monitor](https://user-images.githubusercontent.com/73053777/187196396-601179bc-e563-4512-868a-cea1b9fda5cc.jpg)
![Meldung LaserGRBL](https://user-images.githubusercontent.com/73053777/187196435-7ec055f6-c64c-4a7a-9d84-507b66c4be06.jpg)

**Comment by hans-de** [comment]
Take Care that you have a complete Image. Its 4GB on size. I had the First time a similar Problem because the downloaded Image was broken 

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Aug. 29, 2022 at 14:01 schrieb ***@***.***>:   


I bought this board

These are the error messages in LaserGRBL and about Serieller Monitor

**Comment by Dettinger-15** [comment]
I have take this firmware from the MKS Githup firmware folder to flash it on the board with the ESP32-Chip:
V2.0.8_H35_20211222_n.bin
it is has only 132kB.

**Comment by hans-de** [comment]
Thats the Problem.Click on the Firmware to Open the folder and Download it from there. If you do a right click its corrupted.I did the Same mistake.

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Aug. 29, 2022 at 19:26 schrieb ***@***.***>:   


I have take this firmware from the MKS Githup firmware folder to flash it on the board with the ESP32-Chip:
V2.0.8_H35_20211222_n.bin
it is has only 132kB.

**Comment by Dettinger-15** [comment]
Hallo hans-de,
Thank you very much, it is clear that the firmware update cannot work with the 132kB file.
