### ISSUE TITLE
no cnc firmware in zip folder

### ISSUE THREAD

**Issue by Lazarus-Rising** [makerbase-mks/MKS-DLC32#28]
as it says, I downloaded the zip file for cnc normal and when I unzip it there's nothing there.
is a cnc version available?

**Comment by trashypopashy** [comment]
This one is downloadable: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/CNC/Normal

**Comment by Lazarus-Rising** [comment]
Thanks but when I download it and extract using iZarc there is absolutely nothing in the folder!

**Comment by trashypopashy** [comment]
There is no need to take the .zip-file. Just click on the link, posted above, click on the file-link again and then You have a download-button on the right. This way, You get the .bin-file itself.

**Comment by Lazarus-Rising** [comment]
Hi, I've tried that and I can't find a download button. Please tell me I'm not senile just yet!
![image](https://user-images.githubusercontent.com/83884442/141454172-59b050b9-f185-4bec-8419-9b3eb9cb6ff0.png)

**Comment by trashypopashy** [comment]
click on the yellow marked area:

![image](https://user-images.githubusercontent.com/53164150/141462240-14830b7e-e7e3-4bb5-a31f-b48b1b87aec7.png)
-----------------------------------------------------------------------

...then...

-----------------------------------------------------------------------


![image](https://user-images.githubusercontent.com/53164150/141462325-2dc6e346-f798-4bf0-9134-0c36843b4d2b.png)

**Comment by Lazarus-Rising** [comment]
I'd done all that and it turns out it was file associations setting in IZarc!

Thanks for your help and patience!
