### ISSUE TITLE
Latest Firmware make the board reset when connecting to web UI

### ISSUE THREAD

**Issue by pnt-thiago** [makerbase-mks/MKS-DLC32#280]
Hi, newer firmware version than V2.0.8_H35_20211222_N makes the board unusable as it resets every time I connect to the web UI. Please stop joking around these firmware updates and open source the code so that we, who understand a little, can help you.

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
