### ISSUE TITLE
TMC 2160 driver -> dlc32

### ISSUE THREAD

**Issue by vfear** [makerbase-mks/MKS-DLC32#283]
Please, give the microstep jumper switching scheme on dlc32 for this external driver.  
I connect it via MKS CD 57/86.
![image](https://user-images.githubusercontent.com/12184628/190260146-53f96b97-655a-41b1-8460-be532ac49277.jpeg)
![image](https://user-images.githubusercontent.com/12184628/190260856-4cb49324-2ac0-4424-9f3d-3744172cde13.jpeg)
![image](https://user-images.githubusercontent.com/12184628/190261651-845ee1e2-4385-4e5b-ba74-394cc1b1d553.jpeg)

for example: if i want microstepping 1/8 what should be changed on the main board?  or switch only on the driver?

**Comment by abinoer** [comment]
![972c5031a433e0561a91d82f5e9e945](https://user-images.githubusercontent.com/96047125/222360827-5886b4bb-109a-45c7-8e82-687e207284fa.png)

**Comment by LeSpectre25** [comment]
> hahaha...Barton Dring send my nice Adapters
> 
> ![IMG_20220609_161239402(1)](https://user-images.githubusercontent.com/82659592/190345763-e346aea2-ec8e-453f-890d-49f88e709200.jpg)
> 
> Why? Because on the Y-axis two motors have to share one driver..so it's almost plug n play and I just have both signals at the outputs of the Y-axis and it runs really smooth, clean, quiet and without problems.

Good day, Could you please tell me what adapters are being used on the DLC board in place of the stepper drivers?
