### ISSUE TITLE
MKS-DLC32 v2 motherboard Connection lost.

### ISSUE THREAD

**Issue by Gerd12** [makerbase-mks/MKS-DLC32#286]
For some reason the controller shuts down completely after about 1.5 minutes of working. Laser stops, controller stops, and touch screen goes black. After about 2.0 minutes, the motherboard starts again. The touch screen lights up, X and Y axis numbers all returned to 0.0. Is there any way to continue from when / where the CONNECTION was LOST.
Why does the motherboard and screen loose power anyway??  This happens in LIGHTBURN and LASER GRBL.

![89EE6146-694B-473C-9D4B-E4A409A9717A](https://user-images.githubusercontent.com/92945367/192616059-9f8be043-49a0-4a09-a1eb-56fd25741fab.jpeg)

**Comment by Gerd12** [comment]
Ausgetauscht gegen Neu, Reset und Startknopf.  Im Moment funktioniert alles gut.

**Comment by danielinkiel** [comment]
Die Boards sind gut, aber scheinbar sehr empfindlich was Schwankungen angeht (nachvollziehbar). Deshalb gerade bei Bastelei ausreichend dimensionieren.

Viel Erfolg weiterhin.

**Comment by abinoer** [comment]
This should be related to the power supply, power cord and other external equipment you use. Please check it yourself
