### ISSUE TITLE
SORT IT OUT

### ISSUE THREAD

**Issue by Insigma1** [makerbase-mks/MKS-DLC32#288]
So i have  been waiting 3 months for MKS to sort their dam firmware out, multiple issues reported on the latest version, I am stuck with an older version and frustrated with waiting are you lot going to fix this or what? 

If you're not then can please kindly release the source code so we can this is a joke!

**Comment by tbsmnea** [comment]
I see the same way, MKS is getting worse and worse

**Comment by 3Dangel** [comment]
have you guys tried this?
https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE/tree/main/Firmware/Grbl_Esp32

> So i have been waiting 3 months for MKS to sort their dam firmware out, multiple issues reported on the latest version, I am stuck with an older version and frustrated with waiting are you lot going to fix this or what?
> 
> If you're not then can please kindly release the source code so we can this is a joke!
