### ISSUE TITLE
how to connect my neje laser head??

### ISSUE THREAD

**Issue by djepsylon** [makerbase-mks/MKS-DLC32#289]
hi,
I have a NEJE 30 laser head and the dlc32 card. I searched to find how to connect the head correctly to the motherboard but I found everything and its opposite. Could you once and for all tell me what is the correct way to connect the laser head to the board?
I am attaching an image of the laser in question
thank you.
![H5d9cd693e9f540a0a927bfb2638a1b5f5](https://user-images.githubusercontent.com/96573654/194730122-eb4a309c-73f6-46a9-93ef-10274f21e6ac.jpg)

**Comment by djepsylon** [comment]
i precise that i have a 30A 12V power unit and the stock power unit of the laser. i want to put the laser and the card on the 30A power unit but if it's better or mandatory 2 power supplies I can do it too

**Comment by abinoer** [comment]
Sorry, limited energy, not timely reply

Please refer to the instructions or talk to the customer after sales for details

https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf
