### ISSUE TITLE
MKS- DCL32 slowing down when engravering photos

### ISSUE THREAD

**Issue by dzikk** [makerbase-mks/MKS-DLC32#290]
Hi
I bought Makerbase MKS-DLC32 mobo for scuplfun s9 laser engraver but I have the same problem like with mobo based on Atmega328.
Simplify - its slowing down when photo is engraving and because of this photos looks ugly and expiring time does not match to calculation. I updated SW to the latest version but does not improve

https://user-images.githubusercontent.com/22121054/195652934-3f0b6242-38ce-4a32-bd27-d50e5c58b2db.mp4

https://user-images.githubusercontent.com/22121054/195652947-3ae3bb5f-a034-4d04-96a3-3e64fad59d2a.mp4

**Comment by abinoer** [comment]
Check that the acceleration and maximum speed are consistent, and that the firmware has been updated
