### ISSUE TITLE
Reversing X-Y displacements on the TS-35-r display

### ISSUE THREAD

**Issue by FMD14** [makerbase-mks/MKS-DLC32#292]
I just installed an MKS DLC32 v 2.1 card with a TS-35-R screen with the latest version CoreXY frimware V2.10_H35_2022_0704_C_ZX_001.bin
On the screen the movements are reversed while on laserGrbl or lightburn and the web application move in the right direction 
How to solve this problem?

**Comment by manuelchaves** [comment]
Hello, change the position of the wires in the connectors of the stepper motors

**Comment by hans-de** [comment]
Thats a Bug. The Display control xchange the direction. You can live with it, Install an older version with Others Bugs or wait for s fixed version. I decided the 4st Option. Return to sender and by a better board. The Hardware is pretty good, but the Software made me crazy.

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Okt. 18, 2022 at 12:23 schrieb ***@***.***>:   


I just installed an MKS DLC32 v 2.1 card with a TS-35-R screen with the latest version CoreXY frimware V2.10_H35_2022_0704_C_ZX_001.bin
On the screen the movements are reversed while on laserGrbl or lightburn and the web application move in the right direction
How to solve this problem?

**Comment by FMD14** [comment]
I just installed version 2.08 the axes work
But I can't configure my limit switches
How to fix this problem
I just requested a refund for the card and screen
Which 32-bit card should I buy for CoreXy
because I feel like MKS does nothing to fix bugs 
They are there to sell and that's all

**Comment by FMD14** [comment]
I just asked for the refilling of the card and the screen near the seller is not winning
Which 32-bit card should you turn to have correct results for corexy laser

**Comment by abinoer** [comment]
The display moving x backwards has been fixed

**Comment by abinoer** [comment]
The display moving x backwards has been fixed

**Comment by stephendaley** [comment]
how was it fixed
