### ISSUE TITLE
Mks dlc32 wont connect with laptop

### ISSUE THREAD

**Issue by Obliv88** [makerbase-mks/MKS-DLC32#294]
I have problems with motherboard mks dlc32 it wont connect to my laptop. Lamp 3v3 is not on when i connect usb, other two lamps are on.
Do you know whats problem ?

**Comment by JimmyWeber** [comment]
I have the same problem did you figure out what was happening?

**Comment by Obliv88** [comment]
> I have the same problem did you figure out what was happening?

Yes, i contacted firm that build it and they said it is burned . This is unrepairable. So we need to get a new one

**Comment by abinoer** [comment]
It should be something that's broken or there's a short circuit somewhere
