### ISSUE TITLE
mks dlc32 firmware seem to be open source soon

### ISSUE THREAD

**Issue by kweilim98** [makerbase-mks/MKS-DLC32#295]
![image](https://user-images.githubusercontent.com/66898187/198329943-fc92daf8-d8cc-4b52-9fcc-4d2c475ba370.png)

**Comment by Plottmania** [comment]
lol

**Comment by kweilim98** [comment]
The lasted source code have been released in the new MKS dlc32 firmware

**Comment by liamgibbins** [comment]
Heres the Released firmware..
https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE/tree/main/Firmware

Also they have a discord.
https://discord.gg/Hmz2UwrCnu

5 mins of looking gave me this info.

**Comment by makerbase-mks** [comment]
Yes, has been openned source
