### ISSUE TITLE
MKS-DLC32 Laser V2.20_H35_2022_1101_N_ZX_002.bin Y-axis problem

### ISSUE THREAD

**Issue by josefosantos** [makerbase-mks/MKS-DLC32#297]
In V2.10_H35_2022_0621_N_ZX_001.bin firmware, the x-axis and the y-axis from the machine were inverted from lightburn.
In this new firmware update (V2.20_H35_2022_1101_N_ZX_002.bin), the x-axis is fixed, but the y-axis still inverted.
The machine have the origin in Rear Left and this are the configurations:

$$
$0=10
$1=255
$2=0
$3=2
$4=0
$5=0
$6=0
$10=0
$11=0.010
$12=0.002
$13=0
$20=0
$21=1
$22=1
$23=5
$24=300.000
$25=1000.000
$26=250.000
$27=1.000
$28=1000.000
$30=1000.000
$31=0.000
$32=1
$50=0
$38=1
$40=1
$100=160.000
$101=160.000
$102=160.000
$103=100.000
$104=100.000
$105=100.000
$110=12000.000
$111=5000.000
$112=18000.000
$113=1000.000
$114=1000.000
$115=1000.000
$120=800.000
$121=300.000
$122=1500.000
$123=200.000
$124=200.000
$125=200.000
$130=600.000
$131=400.000
$132=50.000
$133=300.000
$134=300.000
$135=300.000

This is the video explain the problem:
https://youtu.be/IovmWh61kpc

If someone can help me, please give some tips.
Thank you.

**Comment by Mungbeanz** [comment]
Have you tried the invert masks?  As long as the direction of the UI and the home function is the same.
use the grbl settings for this as they are shared.  This firmware seems very broken.  2.08 seems to be the most stable.

![image](https://user-images.githubusercontent.com/33512163/201491384-b49cc7bb-1ca5-4756-ab95-7c1e3535b4c8.png)

**Comment by Tong6998** [comment]
What a lot of people seem to be misunderstanding is this:  

In both the Web interface, and any outside software (lightburn, Grbl, etc) the machine movement correspond to the input you provide, X- moves negative, X+ moves Positive, Y- moves negative, Y+ moves positive.  

**HOWEVER,** when using the included touchscreen the axis movement is not correct in the direction.  In this case it's the Y.  

If we invert the mask, then yes the screen will move correctly, but EVERYTHING else will move incorrectly.  This leads to the conclusion that the machine firmware is built correctly but the screen button portion of the firmware is incorrect. Especially seeing as the last version had both axis's suffering from same problem.

To correct this the firmware must be rebuilt with the Y correction: in the newly released firmware source for the board, the file located at grbl_esp32/src/mks/mks_draw_move.h lines # 49 and 50 must be swapped?  unsure as I have yet to successfully rebuild from source.

**Comment by josefosantos** [comment]
> Have you tried the invert masks? As long as the direction of the UI and the home function is the same. use the grbl settings for this as they are shared. This firmware seems very broken. 2.08 seems to be the most stable.
> 
> ![image](https://user-images.githubusercontent.com/33512163/201491384-b49cc7bb-1ca5-4756-ab95-7c1e3535b4c8.png)

Hello friend, yes I try, it changes in the two platforms, one have to be wrong.

**Comment by josefosantos** [comment]
> grbl_esp32/src/mks/mks_draw_move.h



> What a lot of people seem to be misunderstanding is this:
> 
> In both the Web interface, and any outside software (lightburn, Grbl, etc) the machine movement correspond to the input you provide, X- moves negative, X+ moves Positive, Y- moves negative, Y+ moves positive.
> 
> **HOWEVER,** when using the included touchscreen the axis movement is not correct in the direction. In this case it's the Y.
> 
> If we invert the mask, then yes the screen will move correctly, but EVERYTHING else will move incorrectly. This leads to the conclusion that the machine firmware is built correctly but the screen button portion of the firmware is incorrect. Especially seeing as the last version had both axis's suffering from same problem.
> 
> To correct this the firmware must be rebuilt with the Y correction: in the newly released firmware source for the board, the file located at grbl_esp32/src/mks/mks_draw_move.h lines # 49 and 50 must be swapped? unsure as I have yet to successfully rebuild from source.
> 
> Otherwise it's: Grbl_Esp32/src/mks/MKS_draw_move.cpp lines 44 and 45

Hello friend, where I can find the firmware to make the changes? The MKS-DLC32 is open source?

**Comment by abinoer** [comment]
Adjust by setting the value of $3 in the parameter configuration

Source：https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE

**Comment by guldokat** [comment]
Hello, have anybody find a solution for this problem. ?
