### ISSUE TITLE
Z-probe not work

### ISSUE THREAD

**Issue by ClaudeHerzig** [makerbase-mks/MKS-DLC32#30]
Z-probe (G38.2 Z-10 F20) works with DLC32_V2.0_D2.00.3_H35_ 公 版 _1108_N.bin but the switch still does not work

**Comment by ClaudeHerzig** [comment]
Z-probe (G38.2 Z-10 F20) works with DLC32_V2.0_D2.00.3_H35_ 公 版 _1108_N.bin but the switch still does not work

**Comment by mks-viva** [comment]
Refer to #31
