### ISSUE TITLE
TS24-R v2.0 with DLC32 2.1

### ISSUE THREAD

**Issue by NVLMagic** [makerbase-mks/MKS-DLC32#301]
How should it work? I plugged in EXT1 and EXT2 (in correct slots) and it does nothing.
If I cross connect (EXT1 to EXT2 and EXT2 to EXT1) then the LCD light turn on and the DLC has a constant beep.

What else should I configure, connect, switch to make the display work?

**Comment by abinoer** [comment]
Please try to re-write the firmware
