### ISSUE TITLE
Z-probe not work

### ISSUE THREAD

**Issue by ClaudeHerzig** [makerbase-mks/MKS-DLC32#31]
Z-probe (G38.2 Z-10 F20) works with DLC32_V2.0_D2.00.3_H35_ 公 版 _1108_N.bin but the switch still does not work and no stop

**Comment by solawc** [comment]
> Z-probe (G38.2 Z-10 F20) works with DLC32_V2.0_D2.00.3_H35_ 公 版 _1108_N.bin but the switch still does not work and no stop

The Z_Probe on the motherboard is actually used as the interface of the sensor. Originally, the sensor was used for extended use, but then the Z axis of the cnc was considered, so the function will be re-adjusted in the CNC version.

**Comment by ClaudeHerzig** [comment]
we want to use it to focus the CO2 laser

**Comment by makerbase-mks** [comment]
@ClaudeHerzig Z_Probe can work on the lastest released firmware now.
