### ISSUE TITLE
TTL laser wiring

### ISSUE THREAD

**Issue by mslmkytz** [makerbase-mks/MKS-DLC32#311]
hello the laser i use is ATOMSTACK A5 PRO 40W
TTL output 2-wire + .- single cable. DLC32 V2.1 I am using
How should the cable assembly of my TTL output 3-wire laser be?

**Comment by manuelchaves** [comment]
Recommended is to share the GND with the laser and the TTL and the 12/24V output and the GND trigger a power MOSFET driver, this way you preserve the output of the DLC32 like these
![M-dulo-de-carga-atual-alta-25a-1](https://user-images.githubusercontent.com/8344682/209802600-3d9e58c0-97ca-4fc1-9a9e-930afd65023e.jpg)
![M-dulo-de-substitui-o-rel-fr120n](https://user-images.githubusercontent.com/8344682/209802602-55050162-42a4-4242-96e3-09ce5d6b7b5b.jpg)

**Comment by abinoer** [comment]
> Recommended is to share the GND with the laser and the TTL and the 12/24V output and the GND trigger a power MOSFET driver, this way you preserve the output of the DLC32 like these ![M-dulo-de-carga-atual-alta-25a-1](https://user-images.githubusercontent.com/8344682/209802600-3d9e58c0-97ca-4fc1-9a9e-930afd65023e.jpg) ![M-dulo-de-substitui-o-rel-fr120n](https://user-images.githubusercontent.com/8344682/209802602-55050162-42a4-4242-96e3-09ce5d6b7b5b.jpg)

Yes, this connection is recommended
