### ISSUE TITLE
Space in wifi SSID

### ISSUE THREAD

**Issue by fardeenkhan99** [makerbase-mks/MKS-DLC32#314]
hi, i am trying to connect MKS DLC32 V2.1 board to wifi router. my wifi SSID has a space between 2 words. the board is not connecting to the router as after setting the router name, when i enter [ESP100], the wifi SSID is displayed without the space. i cannot change the router SSID, as i have many other devices connected to it.

**Comment by abinoer** [comment]
Names are supported with Spaces. If you don't have a screen, you can use MakerbaseTOOL to connect, or you can update the latest firmware to check
