### ISSUE TITLE
MKSLaserTool V2.04 Failed to execute script

### ISSUE THREAD

**Issue by manuelchaves** [makerbase-mks/MKS-DLC32#319]
Hi, MKSLaserTool V2.04 crash after install.
WIndows 10 64 bits
Any solution?
Tks
![Sem título](https://user-images.githubusercontent.com/8344682/211142363-f7878c5d-6fff-4c6d-bc10-c2c49a905042.png)

**Comment by manuelchaves** [comment]
Hi, I found a solution, run it in compatibility mode

**Comment by abinoer** [comment]
Decompress the software before installing it

**Comment by nareshhham** [comment]
Run as administrator
