### ISSUE TITLE
Whats really new on the revision 2

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#32]
In changelog @makerbase-mks / @mks-viva / @solawc wrote down what changed from DLC32-V1.1 to DLC32-V2. Can someone explain the following changes a bit more detailed?

1.) Some io function adjustments
2.) Optimize the driver circuit
3.) Optimize the laser and spindle circuit

**Comment by mks-viva** [comment]
I will to perfect it

**Comment by mks-viva** [comment]
I has update hardware readme, so, i will close this issues.

**Comment by trashypopashy** [comment]
So with the io function adjustments the firmware for a V2-board will not work for V1-Boards, right?
