### ISSUE TITLE
Air Assist and Probe 

### ISSUE THREAD

**Issue by concuus** [makerbase-mks/MKS-DLC32#324]
Hello, I have installed the latest version of COREXY TS35 on my DLC32 V2.1 card.
The system works without any problems, but I have a problem when I install air assist and probe.
Air Assist machine starts to work as it works, the probe seems to be triggered even though it is not triggered, how can I change them? 

Edit: E-Stop also works in reverse

**Comment by 3Dangel** [comment]
> Hello, I have installed the latest version of COREXY TS35 on my DLC32 V2.1 card. The system works without any problems, but I have a problem when I install air assist and probe. Air Assist machine starts to work as it works, the probe seems to be triggered even though it is not triggered, how can I change them?
> 
> Edit: E-Stop also works in reverse

may be it is the config in Grbl that you might be missing?

**Comment by concuus** [comment]
you're right, but I couldn't find enough documentation in my language. If there is a link that shows the config settings step by step, let me try again.
