### ISSUE TITLE
Still no Z-axis in Laser firmware...

### ISSUE THREAD

**Issue by alfrankgit** [makerbase-mks/MKS-DLC32#33]
Why is there still (like with the old DLC board) no Z axis in the laser firmware?
I have built a Core XY Laser with a Z axis.
GRBL itself does support that configuration!

**Comment by makerbase-mks** [comment]
Please update the latest firmware: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/TS35/Laser/CoreXY, it enable the Z axis defaultly.

**Comment by ElBorba** [comment]
when will a corexy cnc firmware for ts24 be released?
