### ISSUE TITLE
Web-Interface is missing some functions...

### ISSUE THREAD

**Issue by alfrankgit** [makerbase-mks/MKS-DLC32#34]
The web-interface is missing some important functions when compared to the touchscreen interface.

This is currently about the Laser Core XY firmware "DLC32_V2.0_D2.00.3_H35_8M_1108_C".

No labels (X-, X+, Y-, Y+) on the axis buttons.
No Z axis at all (also missing on the touchscreen).
No Unlock button.
No HHome button (whatever its functionality is).
No Laser power adjustment.

PS: How can the Update WebUI button in the About menu be used? Is there such an update available?

PPS: This is the version information in that menu and it differs a lot from the actual firmware file:
Board Version: DLC32 V003
Firmware: DLC32 V1.10C

**Comment by solawc** [comment]
thank you for your feedback

**Comment by Ondrashek** [comment]
In firmware/TS35/Laser/Normal/Board_V2.0/version 2.0.4 on webUI -> SD File menu I am not able to close menu [marked with red circle].
Safari - iOS 15.1 - iPhone 13 Pro

![IMG_4331](https://user-images.githubusercontent.com/8090571/143765909-4dbdf9e8-98db-4117-8e79-f01707be3ec2.jpg)

**Comment by abinoer** [comment]
@alfrankgit 
The functionality you proposed has been added, please update the firmware
