### ISSUE TITLE
Air Assist, GRBL version in LightBurn and Z with rotary roller

### ISSUE THREAD

**Issue by manuelchaves** [makerbase-mks/MKS-DLC32#346]
Hi.
I have some questions:

- Which pin I use to connect the air assist?

- LightBurn, I configure it as GRBL, GRBL-LPC, GRBL-M3 or another controller?

- Its possible use the Z axis pin, without function until now, to drive the rotary roller?

Grateful

**Comment by TimoFeick** [comment]
You can use G and SCL. I use an SSR with low voltage trigger (SCL delivers only 3.3v).
In my case a SSR-40DA with an small air compressor. Don't forget to use M7 for Air Assist in LightBurn. 
![Hardware Wiring1](https://user-images.githubusercontent.com/125218097/221275493-6da5baa3-9482-4444-9040-c2cecd9282f0.png)

You can configure it as GRBL.

**Comment by manuelchaves** [comment]
> You can use G and SCL. I use an SSR with low voltage trigger (SCL delivers only 3.3v). In my case a SSR-40DA with an small air compressor. Don't forget to use M7 for Air Assist in LightBurn. ![Hardware Wiring1](https://user-images.githubusercontent.com/125218097/221275493-6da5baa3-9482-4444-9040-c2cecd9282f0.png)
> 
> You can configure it as GRBL.

Tks
