### ISSUE TITLE
dlc_cfg.txt update fails...

### ISSUE THREAD

**Issue by alfrankgit** [makerbase-mks/MKS-DLC32#35]
Using the current firmware DLC32_V2.0_D2.00.3_H35_8M_1108_C.bin on the MKS DLC32 V1.1 board
the included dlc_cfg.txt update fails shortly before the end of the progress bar.

This is at the end of the file and it doesn't seem to match the firmware file:
/--Version Configrations-----//
//--Used to be displayed on About Menu-----//
//board_info_1
BoardName:MKS_DLC32
//board_info_2
BoardVersion:V2.0
//board_info_3
FirmwareVersion:V1.0

**Comment by trashypopashy** [comment]
Maybe this could help You: #9

**Comment by alfrankgit** [comment]
Nope. 
Where's the new cfg file that worked for you?

**Comment by alfrankgit** [comment]
Oh, great, not the one from the hidden V1.x fork works but the V2.x one from here:
https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware

**Comment by trashypopashy** [comment]
The only impprtant thing is, that You need to add $133, $134 and $135.
