### ISSUE TITLE
What`s happen with Source Code release?

### ISSUE THREAD

**Issue by m3dkata** [makerbase-mks/MKS-DLC32#36]

**Comment by solawc** [comment]
> _No description provided._

Do you want to ask what changes have been made to the source code?

**Comment by trashypopashy** [comment]
I guess, the meaning is, that we all want the code to be open source.

**Comment by m3dkata** [comment]
We all want the code to be open source! Issue #10 
![1](https://user-images.githubusercontent.com/91957938/143063223-ab6b2480-a4cd-4a34-a848-45ac0344a031.png)

**Comment by bnorth12** [comment]
So is MKS-DLC32 a unique code base or s it based on previous open source efforts?

**Comment by bnorth12** [comment]
Is MKS DLC32 based on or branched from GRBL_ESP32? Getting the PIN definitions assigned would be good.

**Comment by RandomHacks-Git** [comment]
> Is MKS DLC32 based on or branched from GRBL_ESP32? Getting the PIN definitions assigned would be good.

You can check the pins for whatever board version you have on the [hardware folder](https://github.com/makerbase-mks/MKS-DLC32/tree/main/hardware), it's the pin.pdf file

**Comment by capi92** [comment]
Any update on this ?

**Comment by 0727fqh** [comment]
When will open source DLC32? MKS-DLC32 is a modified code based on Bdring/Grbl_Esp32, right?

**Comment by simulz** [comment]
source code please~

**Comment by serial-tintypist** [comment]
I would also like to know when the source code will be released (as the explicit promise of it becoming open source was an important part of my decision to switch over to MKS DLC32 in the first place).

**Comment by trashypopashy** [comment]
Same here...!

**Comment by jerhole** [comment]
Was thinking on buying this controller, as I've went with mks on all of my printers. Though it seems there updates to older products is non-existent. Still waiting on laser support (or at the very least, instructions) from the nano V3. With all of the issues I'm reading on, from people that have purchased this controller,and the lack of follow through of open sourcing (what sounds to be a derivative of open source software, so should've been in the first place}. I'm about fed up with mks desire to pump out products half cocked. Still can't use mks WiFi with standard marlin neither. Get a grip. Finish the products and importantly the documentation of stuff youre already filling the landfills with. Why not focus on a handful of really good products, with good user experience, and make a good reputation that way. Also, while trying to not mass produce so much stuff, to add to the massive pollution problem we have. Money is gonna do nothing when this planet ceases to sustain us. Be a part of the solution, not greedy capitalistic cut throats

**Comment by makerbase-mks** [comment]
Code open source late but finally here: https://github.com/makerbase-mks/MKS-DLC32-FIRMWARE
