### ISSUE TITLE
DLC32 v2 Laser is always on

### ISSUE THREAD

**Issue by sharknetwork24** [makerbase-mks/MKS-DLC32#383]
Everything works perfectly except that the laser is always on and to turn it off I have to disconnect the general power supply.
I would like to know if the problem has been solved, or if it is a defect of the Board DLC32 v2 that does not work.
Can it be solved or should the BOARD be replaced?
Thanks for the replies.

**Comment by sharknetwork24** [comment]
I connected everything correctly.
I attach image of the laser module where the DLC32 v2 board is connected to the laser module

![TTL PWM](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/532f31b1-debf-4380-a0a8-b0c6e5cd00e3)

![PWM TTL LASER](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/0f97d752-c1b0-4208-93da-848011b361c7)

![Laser TTL-PWM](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/853db3ee-ef9b-40b1-8a18-2f1913f44d02)

**Comment by sharknetwork24** [comment]
Is it possible to have a wiring diagram to understand where the problem lies?
And the mosfet to replace Q1 (WSF40N10)?
On J18 I always have a voltage of 12.35V

Ho trovato questo ma non so se è corretto.
![141254561-9beff8f3-cf33-4f91-b388-e8c52febef84](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/646f7b90-ea4f-45c8-b9b0-b34ce19dde63)

**Comment by 3Dangel** [comment]
don't use the TTL
USE THE Spindle.
if you found the schematic of v2.x then chech with the schematic of V1.x and you will see the differences between the two. 
V 1.x will work. V2.x won't.

**Comment by sharknetwork24** [comment]
> don't use the TTL
> USE THE Spindle.
> if you found the schematic of v2.x then chech with the schematic of V1.x and you will see the differences between the two. 
> V 1.x will work. V2.x won't.
> 

Is the spindle output ok to control the laser?  
So you're telling me that the 3-pin TTL output doesn't work in version 2.1 boards?

**Comment by sharknetwork24** [comment]
If anyone knows how to make the links please use the picture and re-post with the correct links. 
Other people may benefit. 
Thank you

![IMG-20230610-WA0004.jpg](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/4de72c69-a52c-4c5b-9445-803e4c65422c)

**Comment by sharknetwork24** [comment]
May be of help to others who have the same Laser.

![IMG-20230613-WA0004.jpg](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/68c077e0-a8bb-4838-8ffc-3a873716f8f4)

![IMG-20230613-WA0005(1).jpg](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/640f8043-9cdf-4bfa-973e-c3e9dae93382)
