### ISSUE TITLE
how to connect emergency stop switch

### ISSUE THREAD

**Issue by Enzo-Enz** [makerbase-mks/MKS-DLC32#385]
hello guys

could you please tell  me how to connect emergency stop switch for mks dlc32?

**Comment by manuelchaves** [comment]
Reset 
![reset](https://github.com/makerbase-mks/MKS-DLC32/assets/8344682/185ab2c6-6461-4782-a51d-8631958cadeb)

**Comment by Enzo-Enz** [comment]
> Reset ![reset](https://user-images.githubusercontent.com/8344682/244958186-185ab2c6-6461-4782-a51d-8631958cadeb.png)

thanks bro
