### ISSUE TITLE
Customize start screen MKS DLC32 Ultimate guide.

### ISSUE THREAD

**Issue by sharknetwork24** [makerbase-mks/MKS-DLC32#390]
STEP 1

We will not use any software that is difficult for many users to understand like VScode or anything else.

Premise:
This was tested with BOARD MKS DLC32 with TS35 display.
Surely this guide also works with TS24 displays, just change the image resolution to 320 x 240 or it's the same as TS 35.
Just do some tests.

Create your personal image strictly with these dimensions:
DIMENSIONS 480 x 320
Save the image in .BMP and rename it to mks_logo.

At the end you will end up with the image created like this:
mks_logo.bmp

WIDTH 480 Pixels
HEIGHT 320 Pixels
DEPTH IN BIT 24
EXTENSION .bmp

Use Photoshop, Corel Draw, Inkscape etc.

EXSAMPLE:
![mks_logo bmp](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/f9555757-218b-46af-b851-17521b7046d7)

**Comment by sharknetwork24** [comment]
STEP 3

Install and open MKS Laser Tool V2.0.4 which you can download here:

https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/tool

Connect your MKS DLC32 board
Open MKS Laser Tool V2.0.4 and click WiFi Configuration Tool

![2 1](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/7cdf0acd-121b-4115-a229-2e7a752a76ed)

**Comment by sharknetwork24** [comment]
STEP 4

Select the COM port and Connect
Enter your WiFi name and Password.

![3 1](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/754a02b6-8bed-4793-a631-d6d3ebed4154)

![3 2](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/c3c3d2a4-3298-4f7a-b26f-697632abe1c4)

Copy the IP address and enter it on your browser.

**Comment by sharknetwork24** [comment]
STEP 5

Opened the browser and opened your IP.
Click on About

![7 1](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/4ac12450-7e10-4ed8-ad34-8008abc59224)

**Comment by sharknetwork24** [comment]
STEP 6

Click on Update WEBUI

![8 1](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/4db54c87-27cf-4afd-a4d2-17191f3c1586)

Now click on:
index.html.gz
mks_logo.bin
Save them to your computer for safety so you can restore them if something goes wrong.

![9 1](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/1b834c8b-228f-4604-89eb-f0f7e56a2d16)

After saving the 2 files just delete mks_logo.bin

![9 2](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/f9241e1f-66b7-4600-913d-fc7e5ad6c23d)

**Comment by sharknetwork24** [comment]
STEP 7

You will find yourself in this situation after deleting the mks_logo.bin file

Now click on Select files and load the .bin image you created earlier.

Loading will be immediate wait 15 sec. about and you will see the 2 files again.

Now disconnect everything and restart the board and as if by magic you will see the screen splash with your custom image.

![9 3](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/d1a60850-0bea-43f4-bd0b-e8983708d6b7)

After uploading your .bin file you will have this situation.

![9](https://github.com/makerbase-mks/MKS-DLC32/assets/82677269/eb392497-ce57-4ccd-9ffa-e639c06c7112)

**Comment by K4o0s2** [comment]
I must tell you that YOU ARE A FUCKING MACHINE!!!!

Fantastic tutorial well worth a video.
I want to point out that I have skipped the MKSLaserTool. I configured my home wifi on the card so when it connects I just have to look at the IP and it works. The rest was easy with your tutorial.
A million thanks for the work and for making life easier for everyone.
Now if we have the latest firmware with the custom screen. As they say in my country... for sample, a button. I leave image of my current screen.

Thank you very much once again! @sharknetwork24
![photo_5812057321449307670_y](https://github.com/makerbase-mks/MKS-DLC32/assets/128930570/7636095b-4b52-4384-b4d5-a800e0cca99b)
(url)

**Comment by sharknetwork24** [comment]
> Devo dirti che SEI UNA MACCHINA DEL CAZZO!!!!
> 
> Tutorial fantastico che merita un video. Voglio sottolineare che ho saltato MKSLaserTool. Ho configurato il mio wifi di casa sulla scheda quindi quando si connette devo solo guardare l'IP e funziona. Il resto è stato facile con il tuo tutorial. Un milione di grazie per il lavoro e per aver reso la vita più facile a tutti. Ora se abbiamo l'ultimo firmware con la schermata personalizzata. Come si dice nel mio paese... per esempio, un bottone. Lascio l'immagine del mio schermo attuale.
> 
> Grazie mille ancora una volta!@sharknetwork24 ![photo_5812057321449307670_y](https://user-images.githubusercontent.com/128930570/248062102-7636095b-4b52-4384-b4d5-a800e0cca99b.jpg) (URL)

I'm glad you managed with my help.
It's nice to help those in need.
Congratulations for the image.

**Comment by K4o0s2** [comment]
I would like, of course with your permission, to make a small video with your tutorial for youtube of course with your nick and links that are convenient for you. What do you think? I am sure that in my country I am not the only one with this problem and you have masterfully solved it

**Comment by sharknetwork24** [comment]
I give you permission to make the video.  Then put the link to the video.

**Comment by burak1000** [comment]
this only works with 2.3 version. but CNC folder doesnt have 2.3 version bin file. pls help. thanks

**Comment by burak1000** [comment]
also i tried on 2.3 laser firmware it's not working too. i dont understand why?
