### ISSUE TITLE
Not starting with MKS TB67S109

### ISSUE THREAD

**Issue by UnleashSpirit** [makerbase-mks/MKS-DLC32#4]
Hi,
Not realy a issue due to firmware (i guess ?), but did not know where to ask.
I just received my MKS DLC32 and wired it like my old MKS DLC, but it did not start.
USB power only, screen start
Removing TMC (MKS TB67S109) and powering with 12VDC supply, screen start

So I guess there is someting to do with the driver ? What do I miss ?
I see a jumper next to the drivers, J37, with 3.3V and 5V annotation, do I have to change it ? (actually on 3.3)

Another question, how many time does it take to update the firmware ? I follow instructions [here](https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware#method-of-upload-firmware), do exactly as the screen capture, but even after 10min still running (seems to be at least)

**Comment by mks-viva** [comment]
Hello! Can you provide a video when you operate it?

**Comment by UnleashSpirit** [comment]
Hi, that was my main question, do I have to switch from 3.3V to 5V :)
I didn't saw this info in the doc, did I miss it ?

Anyway, now with 5V, it starts up, thanks !

**Comment by Berto1157** [comment]
Hello: You've had problems with the TB67S109 drivers on the MKS DLC32 motherboard. Is the motherboard still working? Regards and thanks.
