### ISSUE TITLE
How to change Home screen photo?

### ISSUE THREAD

**Issue by Anderson8153** [makerbase-mks/MKS-DLC32#40]
How to change Home screen photo?

**Comment by solawc** [comment]
> How to change Home screen photo?

Regarding the picture, there is no replaceable form on DLC32, because we compile the picture into source code and save it, which can be modified after open source.

**Comment by makerbase-mks** [comment]
@Anderson8153 Just now, you can send to us to help you to change.

**Comment by Anderson8153** [comment]
@makerbase-mks,
![Logo CNC X 480x320](https://user-images.githubusercontent.com/27018751/142659252-32c1f338-b97f-4452-8742-b4c5072208d6.png)
 Thank you very much, I will send the file

**Comment by Anderson8153** [comment]
@makerbase-mks What software do you use to compile the firmware

**Comment by makerbase-mks** [comment]
@Anderson8153 Sorry for delay, may I know :
1. Your board version, V1.x or V2.x
2. Your machine structure, Normal XY or CoreXY
3. Laser or CNC?

**Comment by Anderson8153** [comment]
@makerbase-mks Hello, no problem!

V2.0  laser normal

**Comment by makerbase-mks** [comment]
[DLC32_V2.0_D2.004_H35_1123_N_change_logo.zip](https://github.com/makerbase-mks/MKS-DLC32/files/7600070/DLC32_V2.0_D2.004_H35_1123_N_change_logo.zip)
@Anderson8153 , please have a try.

**Comment by Anderson8153** [comment]
@makerbase-mks,
At first there is only one problem!
when I give the Frame command on the GRBLlaser the laser doesn't turn on, but it works normal offline

**Comment by Anderson8153** [comment]
@makerbase-mks, The laser fan is always on too, in the latest version that was released on the forum too!

**Comment by Ams-Laser** [comment]
can you please helpme change my logo MKS-dlc32 V2.1 laser firmware V2.30(8M.H35.20221223)
![logo](https://user-images.githubusercontent.com/87819514/227624563-89ea6ffd-465e-4094-b610-47c9e2cb15ed.jpeg)
