### ISSUE TITLE
Documentation LS ESP32 Pro V 2.1 

### ISSUE THREAD

**Issue by ErikLambrechts** [makerbase-mks/MKS-DLC32#456]
Will documentation be added for the LS ESP32 Pro V 2.1 board and/or hardware folder for this board in this repo?

Thanks

**Comment by MJ666** [comment]
It just happend. Firmware and documentation. Very cool.

**Comment by ErikLambrechts** [comment]
Thanks for all the documentation

**Comment by stef-ladefense** [comment]
hi,

where found source firmware for this LS ESP32 Pro V 2.1 ?

I would like to upgrade the wifi to 64 character standards and not 32 as in the current firmware.

thanks

**Comment by MJ666** [comment]
The firmware source is not published yet. From experiance i don't see a good chance this will ever happening.

**Comment by taharctbs22-code** [comment]
> أهلاً،
> 
> أين يمكنني العثور على البرامج الثابتة المصدرية لجهاز LS ESP32 Pro V 2.1؟
> 
> أرغب في ترقية شبكة الواي فاي إلى معايير 64 حرفًا وليس 32 حرفًا كما هو الحال في البرامج الثابتة الحالية.
> 
> شكرًا

Please firmware LS ESP32 PRO V1.1 OR V.2.1 
taharctbs22@gmail.com

**Comment by jdartealaser-cmd** [comment]
Bom dia gostaria de ajuda com minha TTS 55 pro. ela deixou de funcionar o movimento do eixo Y de ir para frente e para tras
