### ISSUE TITLE
Please join Discord for private conversation and send me your e-mail. https://discord.gg/BqjUESKq

### ISSUE THREAD

**Issue by Charus-OV** [makerbase-mks/MKS-DLC32#474]
Please join Discord for private conversation and send me your e-mail. https://discord.gg/BqjUESKq

_Originally posted by @MJ666 in https://github.com/makerbase-mks/MKS-DLC32/issues/457#issuecomment-2056591357_
Hello friend. Could you send me the firmware by email 4arusov75@gmail.com

**Comment by andreivenig** [comment]
Hello, can you help me please with the firmware at andreivenig@gmail.com

**Comment by Nox-jpg** [comment]
Hi, I need help setting up some firmware. Could you help me?

Email: greenyfox08@gmail.com

**Comment by MJ666** [comment]
The latest firmware released here for the Display is working. Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Nox-jpg ***@***.***> Datum: 10.02.25  04:10  (GMT+07:00) An: makerbase-mks/MKS-DLC32 ***@***.***> Cc: MJ666 ***@***.***>, Mention ***@***.***> Betreff: Re: [makerbase-mks/MKS-DLC32] Please join Discord for private
  conversation and send me your e-mail. https://discord.gg/BqjUESKq (Issue #474) 
Hi, I need help setting up some firmware. Could you help me?
Email: ***@***.***
