### ISSUE TITLE
Setup for LCD mks mini12864 V3

### ISSUE THREAD

**Issue by l0v3byte** [makerbase-mks/MKS-DLC32#49]
Hi,
I need help to firmware configure and pin out the LCD marker base LCD  mini 12864 V3.
Thanks for any help

**Comment by makerbase-mks** [comment]
Oh, the firmware supported mini12864 V3 is still being developed now.

**Comment by celio5859-cpu** [comment]
Preciso de ajuda configuro mini 12864 v3 placa mks tinybee v1. 0
