### ISSUE TITLE
Where is the schematic?

### ISSUE THREAD

**Issue by automics** [makerbase-mks/MKS-DLC32#5]
Why not post the schematic?
Lack of scheme strains me greatly to make the order.
I don't want to buy a cat in a bag.

**Comment by mks-viva** [comment]
MKS will upload it

**Comment by makerbase-mks** [comment]
@automics You can find it here:
https://github.com/makerbase-mks/MKS-DLC32/blob/main/hardware/MKS%20DLC32%20V1.1_001/MKS%20DLC32%20V1.1_001%20SCH.pdf

**Comment by HAL9000-ROOT** [comment]
> [@automics](https://github.com/automics) You can find it here: https://github.com/makerbase-mks/MKS-DLC32/blob/main/hardware/MKS%20DLC32%20V1.1_001/MKS%20DLC32%20V1.1_001%20SCH.pdf

dead link: 404 - page not found
The 

main
 branch of 

MKS-DLC32
 does not contain the path 

hardware/MKS DLC32 V1.1_001/MKS DLC32 V1.1_001 SCH.pdf.
