### ISSUE TITLE
Connector manufacturer and model

### ISSUE THREAD

**Issue by lgm42** [makerbase-mks/MKS-DLC32#50]
Hello,
I would like to know which reference from which manufacturer I have to buy connectors to plug to the board ?

Thanks

**Comment by makerbase-mks** [comment]
@lgm42 ,you mean the connectors of DC input? Or other interfaces?

**Comment by lgm42** [comment]
I mean all connectors on the board. Motor connectors, input, etc ...
Are they Dupont, molex, ... ?

**Comment by makerbase-mks** [comment]
OK, the connectors of all XH2.54 are compatible with JST connectors.

**Comment by dreadedhamish** [comment]
This info isn't on the github, listed on sales pages, or in the WIRING MANUAL!
