### ISSUE TITLE
Flash Download Tool 3.9.2

### ISSUE THREAD

**Issue by Ondrashek** [makerbase-mks/MKS-DLC32#52]
With new version of Flash Download Tool 3.9.2 I am not able to flash new firmware. FLASH SIZE missing = tutorial on firmware page is not functional (https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware).

Use MKS Laser Tool instead. (https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/tool)

**Comment by FrancescoIT** [comment]
I also tried and I failed, there are no permissions to write from usb

**Comment by makerbase-mks** [comment]
We found it too, maybe there is a bug for the 3.9.2 version, should wait for the fixing of  Espressif. You can use MKS Laser Tool.
