### ISSUE TITLE
DLC 32 and TMC2209 # Jumper support

### ISSUE THREAD

**Issue by Matze1811** [makerbase-mks/MKS-DLC32#54]
Hi there,

How are the jumpers to be set when using MKS TM2209 drivers.
What other settings have to be made in order to operate the dls32 with the TMC2209.

**Comment by trashypopashy** [comment]
These Jumpers do not change a thing.

**Comment by abinoer** [comment]
@Matze1811 Here is a manual for your reference[https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf](url)
