### ISSUE TITLE
Z axis command on laser normal binary

### ISSUE THREAD

**Issue by Ventus2C** [makerbase-mks/MKS-DLC32#55]
I want to use MKS DLC32 V2.1 with TFT35RV2.0 on laser type K40.
Is it possible to activate Z+ and Z- button on control panel ( as CNC binary version)?
I will use this Z axis to drive Z-table on K40.

Thanks for your help.

Regards

**Comment by RandomHacks-Git** [comment]
Yeah I'm also interested in this feature for exactly the same reason.

**Comment by makerbase-mks** [comment]
Hmm, it is being developed now.

**Comment by sergeinik1313** [comment]
Можно ли активировать Z+ и Z - кнопку на панели управления ( как двоичная версия CNC)?
Я буду использовать эту ось Z для управления

**Comment by abinoer** [comment]
Z-axis control buttons have been added
