### ISSUE TITLE
dlc32 ts35 em português 

### ISSUE THREAD

**Issue by Kleitongie** [makerbase-mks/MKS-DLC32#56]
alguem sabe como colocar pt_br na dlc32 com ts35 ?

**Comment by makerbase-mks** [comment]
What is pt_br ?

**Comment by 21mac** [comment]
> alguem sabe como colocar pt_br na dlc32 com ts35 ?

he wants to set the language (displayed on the TS35) to "pt_br" ("Brazilian Portuguese").

**Comment by Kleitongie** [comment]
> > alguem sabe como colocar pt_br na dlc32 com ts35 ?
> 
> ele quer definir o idioma (exibido no TS35) para "pt_br" ("Português Brasileiro").

ISSO MESMO

**Comment by abinoer** [comment]
Portuguese has been added to laser firmware
