### ISSUE TITLE
Telnet, Websocket connection

### ISSUE THREAD

**Issue by Ondrashek** [makerbase-mks/MKS-DLC32#58]
Add connection for Telnet (:23) or Websocket (ws://, :81).

Both is supported for LaserGRBL, LaserWeb.

**Comment by ahmetbozaci** [comment]
I connected wifi without LCD. I try to connect to LaserGrbl not working. Mks web interface has not much feature. If it is possible to add support telnet or WebSocket ı am waiting for it also.

**Comment by makerbase-mks** [comment]
You can connect through the Telnet, but the port is 8080.

**Comment by Ondrashek** [comment]
> You can connect through the Telnet, but the port is 8080.

Telnet on :8080 working with GRBL! Thank you thank you! Documentation missing. :-P
