### ISSUE TITLE
conectar wfi sem o lcd 

### ISSUE THREAD

**Issue by Kleitongie** [makerbase-mks/MKS-DLC32#59]
como faço pra conectar a placa dlc32 no wifi sem o lcd?

**Comment by 21mac** [comment]
use google translate and find the solution here:
https://github.com/makerbase-mks/MKS-DLC32/issues/23

**Comment by ahmetbozaci** [comment]
Check this issue. solution in there. https://github.com/makerbase-mks/MKS-DLC32/issues/12

**Comment by Kleitongie** [comment]
>EU NAO ENTENDI COMO FAZER
