### ISSUE TITLE
Firmware upload not working

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#6]
I can not upload the CNC_normal Firmware to the DLC32.
![grafik](https://user-images.githubusercontent.com/53164150/133000843-ea08f620-7098-4cef-8ce2-d26c94b2f557.png)

**Comment by mks-viva** [comment]
@solawc Please check if his settings are correct?

**Comment by Igoravg98** [comment]
![try 1](https://user-images.githubusercontent.com/87287704/133014798-8dead942-b6a4-4034-9dca-6e925964d3f8.png)
I'm having a problem uploading the firmware too, the address is always red like this

**Comment by solawc** [comment]
> ![try 1](https://user-images.githubusercontent.com/87287704/133014798-8dead942-b6a4-4034-9dca-6e925964d3f8.png)
> I'm having a problem uploading the firmware too, the address is always red like this

From your prompt, it seems that the serial port you selected is incorrect. Normally on the tool, if the selected serial port and address are correct, it should display green instead of red. Please check if the path of .bin is correct? Address should fill in 0x00 instead of 0 directly

**Comment by Igoravg98** [comment]
![this](https://user-images.githubusercontent.com/87287704/133021350-4a4f9a2b-a9ad-432b-b74b-3eabef63db5b.png)
Now I noticed that the button to add the bin file is not working, this appears here when I try to add the file

**Comment by solawc** [comment]
> ![this](https://user-images.githubusercontent.com/87287704/133021350-4a4f9a2b-a9ad-432b-b74b-3eabef63db5b.png)
> Now I noticed that the button to add the bin file is not working, this appears here when I try to add the file

Since this tool is not developed by us, it is an official tool of ESP32, and I am not aware of its problems. But you can enter a complete path directly above, it is no problem.

**Comment by Igoravg98** [comment]
It was a problem with my computer, I tried it on another one and everything worked out fine, I'm really happy, thanks for trying to help me!

**Comment by solawc** [comment]
> It was a problem with my computer, I tried it on another one and everything worked out fine, I'm really happy, thanks for trying to help me!

Oh, it’s okay, I’m glad to help you solve the problem

**Comment by trashypopashy** [comment]
I solved my problem: I needed not just to start the flashing tool with admin rights, but first change the files properties >> Security >> to "full control"
