### ISSUE TITLE
TMC 2208

### ISSUE THREAD

**Issue by iherbak** [makerbase-mks/MKS-DLC32#60]
Is the DLC32 V2 compatible with TMC2208 drivers?

Thanks

**Comment by Plottmania** [comment]
why not?
Runns withe TMC 2208 / 2209 and no problems : )

**Comment by solawc** [comment]
> Is the DLC32 V2 compatible with TMC2208 drivers?
> 
> Thanks

DLC32 is compatible with 4988/2208/2209, but what you need to know is that the effects obtained by different drivers are of course different. What is adjusted by $0 is the pulse width output from a motherboard to the driver, which can be adjusted according to your needs. And I use the best effect is A4988
