### ISSUE TITLE
MKSLaser app

### ISSUE THREAD

**Issue by Charus-OV** [makerbase-mks/MKS-DLC32#62]
You missed the underscore in the Wi-Fi settings

**Comment by makerbase-mks** [comment]
Oh, sorry, you mean the underscore in ssid or password?

**Comment by Charus-OV** [comment]
> О, извините, вы имеете в виду подчеркивание в ssid или пароле?

Yes. There is no underscore

**Comment by abinoer** [comment]
Have been added
