### ISSUE TITLE
Fw version

### ISSUE THREAD

**Issue by FrancescoIT** [makerbase-mks/MKS-DLC32#65]
I load the FW V2.0.4_H35_20211123_N.bin and the version on the board always remains the old one, even though the upload was successful 
![errore fw](https://user-images.githubusercontent.com/42808825/144897446-20f876ec-074a-48c1-8955-cfc1ce65b678.jpg)

**Comment by una2012** [comment]
I have same problems

**Comment by solawc** [comment]
> I load the FW V2.0.4_H35_20211123_N.bin and the version on the board always remains the old one, even though the upload was successful ![errore fw](https://user-images.githubusercontent.com/42808825/144897446-20f876ec-074a-48c1-8955-cfc1ce65b678.jpg)

Thank you for your feedback. It is true that the version number of this place has not been modified. This question will be modified today. The version number displayed on the screen should have been modified

**Comment by solawc** [comment]
In the new version update, the correct version number can be queried normally through LB, or through $I.

**Comment by FrancescoIT** [comment]
sorry if I ask you here, can you tell me when the pin will be implemented to automatically manage the air assist? 
see issue # 53.
thanks again for the support
