### ISSUE TITLE
Connecting the end stop switch 

### ISSUE THREAD

**Issue by Devil-67** [makerbase-mks/MKS-DLC32#69]
Connecting the end stop switch  

Connecting the end stop switch 

Which two connection pins do I need for mechanical limit switches? 

what does 1034, 1035, 1036 mean ?
![Unbenannt](https://user-images.githubusercontent.com/31169133/145479907-a2b6d05a-f046-4015-a6fb-b6ca3bd99e5c.PNG)

**Comment by deltazerorsan** [comment]
It depends if you use high or low level detection ($5=1 or $5=0)

IO34, IO35 and IO36 are pins of the ESP32. (The letters "i" and "o" not 10)

If you have a normally open switch (NO) you need to connect from ground (GND) to IO or from 5V (five volts) to IO.

If you buy a limit switch with led indication then you need the three wires...

Do a search for some schematics.

Cheers

Rom

**Comment by capi92** [comment]
once wire, end switches are detected but no alarm is raised i.e. motor don't stop moving. 
I guess this is not yet implemented in the SW :-(

Running laser version V2.0.6_H24_20211209_N.bin

**Comment by RandomHacks-Git** [comment]
Did you enable hard limits? ($21) 
They work fine here.

**Comment by Devil-67** [comment]
They work for me too.
But you also have to activate them in the settings.

**Comment by capi92** [comment]
> > once wired, end switches are detected (can see them in console) but no alarm is raised i.e. motor don't stop moving. I guess this is not yet implemented in the SW :-(
> > Running laser version V2.0.6_H24_20211209_N.bin
> 
> Did you enable hard limits? ($21) They work fine here.

I did and while motor are moving, triggering the switch doesn't stop the motion.
I see in console that limit switch is changing status but don't see the alarm message.
I have set limit switch via webUI. Will try via USB, maybe this could explain..
