### ISSUE TITLE
Flashing firmware erase GRBL settings to default

### ISSUE THREAD

**Issue by Ondrashek** [makerbase-mks/MKS-DLC32#70]
I must rewrite grbl settings every time when I flash a new firmware.

Is it possible to avoid this? 

Yeah I know, I can export grbl settings and import it....

**Comment by solawc** [comment]
> I must rewrite grbl settings every time when I flash a new firmware.
> 
> Is it possible to avoid this?
> 
> Yeah I know, I can export grbl settings and import it....

Hello, for the native GRBL, it will save the relevant value to the internal Flash, and use the version number to identify whether the EEPROM value needs to be re-updated. The same is true for DLC32. Each update will also update the corresponding date and version number, so It will also cause you to rewrite.
