### ISSUE TITLE
Unable to find mksLaserTool_V1.X.X software

### ISSUE THREAD

**Issue by lgm42** [makerbase-mks/MKS-DLC32#71]
I've just received my MKS DLC32 and I would like to configure Wifi to be able to connec tto it with my phone.
As I've seen in documentation (https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20Firmware%20Programming%20Instructions.pdf) I have to install mksLaserTool softer on my computer.
I can't manage to find the software. Is there any link where I can find it or Does it exists another way to configure my board ?

**Comment by RandomHacks-Git** [comment]
https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware/tool

**Comment by lgm42** [comment]
So simple ! Sorry for that ! Thanks

**Comment by lgm42** [comment]
I have another question.
Folder you indicate contains the version 1.0.2 that havn't wifi configuration tool option.
How Can I configure the wifi ?

**Comment by RandomHacks-Git** [comment]
I'm not sure about the tool, I'm not a collaborator of this repository.
You can configure wifi through the LCD, if you don't have one this might help: https://github.com/makerbase-mks/MKS-DLC32/issues/12

**Comment by lgm42** [comment]
I finally find a solution.
With serial link I send commands:

> $Sta/SSID=wifi name
> $Sta/Password=wifi password
> $Radio/Mode=STA
