### ISSUE TITLE
GRBL PIN/FUNCTION MISSED

### ISSUE THREAD

**Issue by Cortapalos** [makerbase-mks/MKS-DLC32#73]
In grbl there are 2 functions that I miss on this board. One is the spindle direction control which can also be configured as Laser Enable, and another is the Coolant Enable gcode M8 which can also be used with air assist control. These pins come on the 8bits DLC V1.0 board, why not include them? In arduino it corresponds to pins D13 and A3. Also missing are the inputs for START, PAUSE / DOOR OPEN buttons (A1, A2)
I attach a photo of an 8-bit arduino and how GRBL was thought 
![Arduino](https:
![Grbl_Pin_Diagram_v0 9+](https://user-images.githubusercontent.com/95981130/145689366-0f564770-abf7-4558-b49a-beab720e4e0a.png)
//user-images.githubusercontent.com/95981130/145689321-d3903206-b55e-4438-91db-87aa7d18511a.jpg)
![MKS DLC V2 1](https://user-images.githubusercontent.com/95981130/145689323-6a594fb1-461b-424a-be12-7acd28097af3.jpg)

**Comment by FrancescoIT** [comment]
and for some time we have been asking for a firmware change for this problem but still no results #53

**Comment by makerbase-mks** [comment]
@Cortapalos , new released [V2.0.7_H35_20211213_N_CNC](https://github.com/makerbase-mks/MKS-DLC32/blob/main/firmware/TS35/CNC/Normal/Board_v2.0/V2.0.7_H35_20211213_N_CNC.bin) has added the M7/M8/M9 function(using SCL pin). the spindle direction has no IOs left, we should decide which IO should be used.

**Comment by Cortapalos** [comment]
Great job thanks

**Comment by FrancescoIT** [comment]
thanks great job, I run to update !!!
