### ISSUE TITLE
Engraving problem with Lightburn

### ISSUE THREAD

**Issue by Cortapalos** [makerbase-mks/MKS-DLC32#75]
Lightburn engravings do not use the G0 command, instead they use G1 XY S0 to move without engraving and G1 XY S700 to engrave,
So the problem is that the DLC32 board make pauses between command and command and causes the laser to remain on and burning at a fixed point, the engraving remains with marks and the result is bad. I attach images of the same work done with DLC32 and DLC v2.1
![photo_2021-12-12_11-40-35](https://user-images.githubusercontent.com/95981130/145716871-a4fcbabe-db9c-44e7-8353-defecd333f2c.jpg)
![photo_2021-12-12_11-40-23](https://user-images.githubusercontent.com/95981130/145716873-cd1d97bb-7338-4887-83ce-edf5f9a2ea2f.jpg)

**Comment by abinoer** [comment]
> Lightburn engravings do not use the G0 command, instead they use G1 XY S0 to move without engraving and G1 XY S700 to engrave, So the problem is that the DLC32 board make pauses between command and command and causes the laser to remain on and burning at a fixed point, the engraving remains with marks and the result is bad. I attach images of the same work done with DLC32 and DLC v2.1 ![photo_2021-12-12_11-40-35](https://user-images.githubusercontent.com/95981130/145716871-a4fcbabe-db9c-44e7-8353-defecd333f2c.jpg) ![photo_2021-12-12_11-40-23](https://user-images.githubusercontent.com/95981130/145716873-cd1d97bb-7338-4887-83ce-edf5f9a2ea2f.jpg)

Is lightburn set differently? I didn't find anything like that in my tests
