### ISSUE TITLE
G28.2 X0 and  G28.3 X0 not works

### ISSUE THREAD

**Issue by ClaudeHerzig** [makerbase-mks/MKS-DLC32#76]
G28.2 X0 and  G28.3 X0 not works on firmware V2.0.7_H35_20211213_N_CNC

**Comment by solawc** [comment]
> G28.2 X0 and G28.3 X0 not works on firmware V2.0.7_H35_20211213_N_CNC

Thank you for your feedback, we will find out why

**Comment by solawc** [comment]
I don't know about the command G28.2 X0, can you tell me what kind of phenomenon this will have?
