### ISSUE TITLE
In the laser version, the HHome button works well but does not exist in the CNC

### ISSUE THREAD

**Issue by ClaudeHerzig** [makerbase-mks/MKS-DLC32#77]
In the laser version, the HHome button works well on X,Y but does not exist in the CNC X,Y,Z

**Comment by solawc** [comment]
> In the laser version, the HHome button works well on X,Y but does not exist in the CNC X,Y,Z

Do you mean that in CNC, X, Y, Z cannot return to the mechanical origin?

**Comment by ClaudeHerzig** [comment]
the HHome button on ts35 does not exist on the CNC firmware

**Comment by ClaudeHerzig** [comment]
the HHome button on ts35 does not exist on the CNC firmwar
![HHome](https://user-images.githubusercontent.com/94139046/148654938-fa63d2fb-2012-4b30-b18f-d8ef305e6597.PNG)
e

**Comment by abinoer** [comment]
Fixed, please update firmware
