### ISSUE TITLE
Z axis Control

### ISSUE THREAD

**Issue by arferdz** [makerbase-mks/MKS-DLC32#81]
While this controller is designed for laser, please do not discount that it will be used on spindled cncs.  There is provision for a z axis on the hardware yet it was missed on the app and web controls. Please provide this very important feature too

**Comment by solawc** [comment]
> 

Thank you very much for your feedback, the web function will be updated together in the next firmware update

**Comment by hallskelet** [comment]
For working with a laser machine, this is also an important function. Adjustable tables are often used to set the focus.

**Comment by abinoer** [comment]
Z-axis control buttons have been added
