### ISSUE TITLE
documentation on DLC 32 V2.0

### ISSUE THREAD

**Issue by killrob** [makerbase-mks/MKS-DLC32#82]
Can we please know the function of dip switches in the V2.0?
i have found no infos on that.

**Comment by solawc** [comment]
> 

Yes, the detailed description is in production, and you will get it soon

**Comment by Plottmania** [comment]
This is quite simple : )
Only with Pololu 4988 and 8825 motor drivers the dips work.
So the step resolution can be set here.
With TMC drivers it does not matter what is jumpered there like...

**Comment by killrob** [comment]
> This is quite simple : ) Only with Pololu 4988 and 8825 motor drivers the dips work. So the step resolution can be set here. With TMC drivers it does not matter what is jumpered there like...

And it's ok i have 4899 drivers, the  question is the meaning of the dips, not with which drivers they works

**Comment by Plottmania** [comment]
I hope it helps you a little...

https://plottmania.de/forum/thread/123-mks-dlc-stepper-resolution/

![MKS_Stepper_01](https://user-images.githubusercontent.com/82659592/146760704-e3238ba5-3425-4f85-9f09-7de67fa1b744.jpg)

**Comment by Plottmania** [comment]
...
![steppersolution](https://user-images.githubusercontent.com/82659592/147041000-0549ec97-8381-49b5-97de-3706a4f0c4fc.JPG)

**Comment by makerbase-mks** [comment]
Here is the document: https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf
