### ISSUE TITLE
Post Processor on Normal CNC

### ISSUE THREAD

**Issue by HiuryLima** [makerbase-mks/MKS-DLC32#84]
Hello, I would like to know which post processor I can use in the normal cnc router version of mks dlc32?

I already use grbl.gcode, is there another one that can be used?
![vectric_post](https://user-images.githubusercontent.com/93689036/146850556-c650f36d-8eab-4b8a-92d5-c7a89def91e9.png)

**Comment by makerbase-mks** [comment]
Hello, what does the " post processor" for? DLC32 is compatible with GRBL.nc file format.
