### ISSUE TITLE
TS24-R V2.0 Laser Mode English Language Corrections, Recommendations

### ISSUE THREAD

**Issue by torenich** [makerbase-mks/MKS-DLC32#85]
Currently running firmware V2.07(8M.H24.20211214) on DLC32 V2.1 with TS24-R V2.0.

1. On main screen, instead of "Sculpture" I would recommend "Engrave" (same on the TS35-R V2.0)
2. On Set>wifi, should read "Signal" instead of "Single"
3. On the keyboard when entering the wifi password, the CAPS button is blank. Recommend putting a "^" character, like on the TS35-R V2.0

**Comment by makerbase-mks** [comment]
Thank you very much, we will modify it.

**Comment by torenich** [comment]
Fixed as of FW V2.0.8_H24_20220107_N
