### ISSUE TITLE
Configure through configuration files with error

### ISSUE THREAD

**Issue by trashypopashy** [makerbase-mks/MKS-DLC32#9]
When I configure with the dlc_cfg.txt on a TF-Card, the DLC32 transfers the data, but at the end it shows the following message: 
![20210928_074118](https://user-images.githubusercontent.com/53164150/135029790-154949a0-7bd2-4b9c-88be-7e4b9378f33c.jpg)
I already tried several TF-cards.

**Comment by mks-viva** [comment]
1. Please upload your config to here.
2. Check your SD card, FTA32 and 4096 byte
![image](https://user-images.githubusercontent.com/16629551/135032020-804a4808-3ecb-4447-826b-c3c7475751db.png)

**Comment by trashypopashy** [comment]
> 1. Please upload your config to here.
> 2. Check your SD card, FTA32 and 4096 byte
>    ![image](https://user-images.githubusercontent.com/16629551/135032020-804a4808-3ecb-4447-826b-c3c7475751db.png)
[dlc_cfg.txt](https://github.com/makerbase-mks/MKS-DLC32/files/7241836/dlc_cfg.txt)

**Comment by mks-viva** [comment]
@solawc 
Please check it.

**Comment by trashypopashy** [comment]
With profile do you mean the dlc_cfg.txt?

**Comment by solawc** [comment]
> It works!
> 
> Can You please tell me what the parameters $133 - $135 stand for (this is the only thing, that seemed the change)?

Because there is a verification of the number of configurations in the program, the failure is because the verification did not pass
