### ISSUE TITLE
ts24-R v2.0

### ISSUE THREAD

**Issue by MikeyD6** [makerbase-mks/MKS-DLC32#90]
could you put up some dimensions for the ts24-R v2.0 please. or some stl files for a mount. thank you

**Comment by Ondrashek** [comment]
https://www.thingiverse.com/thing:5173741

**Comment by MikeyD6** [comment]
awesome
Thank you

**Comment by capi92** [comment]
Alternative proposal... https://www.prusaprinters.org/prints/93079-mks-dlc32-box-for-24-lcd-on-20x20-v-slot

**Comment by MikeyD6** [comment]
Yep,
That'll work. Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
