### ISSUE TITLE
Inverted Y axis on 2.4 LCD touch screen

### ISSUE THREAD

**Issue by capi92** [makerbase-mks/MKS-DLC32#93]
Running V2.0.8_H24_20211223_N.bin

Y axis is inverted on LCD, correct behavior via webui or usb.

and btw, version displayed on LCD screen is incorrect, dos display version 20211222 instead of 23 !

**Comment by MKS-hosiey** [comment]
Is the direction of moving the Y axis on the TFT screen different from the direction on the web?

**Comment by capi92** [comment]
Yes it is.

**Comment by torenich** [comment]
Can confirm. When using the touchscreen, Y+ moves the opposite direction, and decrements the Y position.

**Comment by MKS-hosiey** [comment]
Thanks for the feedback, we have reproduced this problem and we will fix it soon

**Comment by solawc** [comment]
The issue has been fixed in the latest update
