### ISSUE TITLE
Lcd

### ISSUE THREAD

**Issue by mikerocklewitz** [makerbase-mks/MKS-DLC32#95]
If i wanted to use my own resistive lcd panel, what kind and how is it wired? Dlc32 2.1

**Comment by makerbase-mks** [comment]
Make sure your lcd panel supports SPI interface and refer to the pins here:https://github.com/makerbase-mks/MKS-DLC32/blob/main/hardware/MKS%20DLC32%20V2.1_003/MKS%20DLC32%20V2.1_003%20SCH.pdf

**Comment by mikerocklewitz** [comment]
> Make sure your lcd panel supports SPI interface and refer to the pins here:https://github.com/makerbase-mks/MKS-DLC32/blob/main/hardware/MKS%20DLC32%20V2.1_003/MKS%20DLC32%20V2.1_003%20SCH.pdf

I need to reopen the question. 8 months after asking im finally modifying a 3018.....

What type of lcd is being used? I see the pinout for spi in the schematics but what is the lcd controller so i use the correct kind.
