### ISSUE TITLE
Position 0 on the axes Normal CNC

### ISSUE THREAD

**Issue by HiuryLima** [makerbase-mks/MKS-DLC32#96]
When I click on the xy position or z position to zero the axes, they still do not zero.
This in the latest version of normal cnc frimware.

I would like to know does anyone have any solutions?
![Screenshot_20220105-235227](https://user-images.githubusercontent.com/93689036/148320692-4ea7915d-c66e-4c9f-8727-6e1176af55c8.png)

**Comment by MKS-hosiey** [comment]
Hello, does your machine have mechanical limits? If it is a limited position, you need to configure the mechanical limit and its trigger level in the configuration; if there is no limit, you need to position first, the position of the positioning is 0, and then after the machine moves, click home, it will Back to 0
