### ISSUE TITLE
Z axis limit switch not working? (2.4" lcd, laser version)

### ISSUE THREAD

**Issue by RandomHacks-Git** [makerbase-mks/MKS-DLC32#97]
Hi, I'm trying to use a limit switch for the Z axis but the board doesn't seem to react to it, no alarm is triggered.
I tried on the "Z" connector (IO34) and the "Probe" connector (IO22) without success. 

I'm using an NO switch connected between GND and the IO pin (I'm using the same configuration for the X and Y axes which work fine). I also tried changing $6 but it didn't make any difference.

I have v2.0 of the board with the 2.4" LCD and the most recent laser firmware.

Help?

**Comment by MKS-hosiey** [comment]
We will update the firmware soon, and the new firmware will fix the problem

**Comment by solawc** [comment]
The latest firmware can be used normally, please update

**Comment by RandomHacks-Git** [comment]
Works fine now, thank you.
