### ISSUE TITLE
Links for MKS-DLC32 firmware ERROR 404 

### ISSUE THREAD

**Issue by daven78** [makerbase-mks/MKS-DLC32#98]
The CoreXY laser firmware link doesn't work.  I would like to download it for MKS-DLC32 board.

**Comment by Ondrashek** [comment]
You can download it: 
https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware

**Comment by daven78** [comment]
Where is it?  The blue link that says "For Laser, CoreXY machine" doesn't work.

[cid:1116d16a-9bb7-4cda-a20b-fcf97ab5bee3]

________________________________

**Comment by Ondrashek** [comment]
> Where is it? The blue link that says "For Laser, CoreXY machine" doesn't work. [cid:1116d16a-9bb7-4cda-a20b-fcf97ab5bee3]
> […](#)
> ________________________________ From: Ondrashek ***@***.***> Sent: Friday, January 7, 2022 1:44 PM To: makerbase-mks/MKS-DLC32 ***@***.***> Cc: daven78 ***@***.***>; Author ***@***.***> Subject: Re: [makerbase-mks/MKS-DLC32] Links for MKS-DLC32 firmware ERROR 404 (Issue #98) You can download it: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmakerbase-mks%2FMKS-DLC32%2Ftree%2Fmain%2Ffirmware&data=04%7C01%7C%7Cfa952fdb6c75489c1dd408d9d21626c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771814855130529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QnHT1CUWV554gmrmb39ZkSfanWJKPmg47olKwvB7muk%3D&reserved=0> — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmakerbase-mks%2FMKS-DLC32%2Fissues%2F98%23issuecomment-1007688254&data=04%7C01%7C%7Cfa952fdb6c75489c1dd408d9d21626c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771814855130529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FHGMLtPTrAhXmyIGrODSyI%2FVhSzNmlt4KiEj9NBVHLU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADCEFVUXKFKHIHOCXYR7SDTUU47CVANCNFSM5LPK463A&data=04%7C01%7C%7Cfa952fdb6c75489c1dd408d9d21626c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771814855130529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z9%2BYkIFIgZ%2BwsPidLWT9aLAoQYs%2FkTSdW54kkgDMkYQ%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cfa952fdb6c75489c1dd408d9d21626c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771814855130529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mabUNGq%2B6CFkTthcP0pgAdzSZJ1znlr%2BHVSmgAGtzw8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cfa952fdb6c75489c1dd408d9d21626c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771814855130529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CVC1NK7anUYeJMN2msZmHYEtfB8c%2FsR7hGDAF5orrHs%3D&reserved=0>. You are receiving this because you authored the thread.Message ID: ***@***.***>

Yes, the blue link in description (readme) have bad url address. I sent you link to firmware tree: https://github.com/makerbase-mks/MKS-DLC32/tree/main/firmware

Select screen version TS24 or TS35 (if you don't have screen from makerbase, you can use one of them -> Laser -> CoreXY -> Board_v1.0 (for board version 1.x - jumpers) or Board_v2.0 (for board version 2.x - red dip switched) -> choose firmware by version.
